{"repo": "home-assistant/core", "pull_number": 136982, "instance_id": "home-assistant__core-136982", "issue_numbers": ["136978", "136978"], "base_commit": "fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5", "patch": "diff --git a/homeassistant/components/swiss_public_transport/icons.json b/homeassistant/components/swiss_public_transport/icons.json\nindex 06a640a06b2705..45cf4713705e63 100644\n--- a/homeassistant/components/swiss_public_transport/icons.json\n+++ b/homeassistant/components/swiss_public_transport/icons.json\n@@ -10,7 +10,7 @@\n       \"departure2\": {\n         \"default\": \"mdi:bus-clock\"\n       },\n-      \"duration\": {\n+      \"trip_duration\": {\n         \"default\": \"mdi:timeline-clock\"\n       },\n       \"transfers\": {\ndiff --git a/homeassistant/components/swiss_public_transport/sensor.py b/homeassistant/components/swiss_public_transport/sensor.py\nindex a0131938a37f9f..c8075a6746cbab 100644\n--- a/homeassistant/components/swiss_public_transport/sensor.py\n+++ b/homeassistant/components/swiss_public_transport/sensor.py\n@@ -56,8 +56,10 @@ class SwissPublicTransportSensorEntityDescription(SensorEntityDescription):\n     ],\n     SwissPublicTransportSensorEntityDescription(\n         key=\"duration\",\n+        translation_key=\"trip_duration\",\n         device_class=SensorDeviceClass.DURATION,\n         native_unit_of_measurement=UnitOfTime.SECONDS,\n+        suggested_unit_of_measurement=UnitOfTime.HOURS,\n         value_fn=lambda data_connection: data_connection[\"duration\"],\n     ),\n     SwissPublicTransportSensorEntityDescription(\ndiff --git a/homeassistant/components/swiss_public_transport/strings.json b/homeassistant/components/swiss_public_transport/strings.json\nindex ef8cc5595e3eff..270cb097e0a3a6 100644\n--- a/homeassistant/components/swiss_public_transport/strings.json\n+++ b/homeassistant/components/swiss_public_transport/strings.json\n@@ -64,8 +64,8 @@\n       \"departure2\": {\n         \"name\": \"Departure +2\"\n       },\n-      \"duration\": {\n-        \"name\": \"Duration\"\n+      \"trip_duration\": {\n+        \"name\": \"Trip duration\"\n       },\n       \"transfers\": {\n         \"name\": \"Transfers\"\n", "test_patch": "diff --git a/tests/components/swiss_public_transport/snapshots/test_sensor.ambr b/tests/components/swiss_public_transport/snapshots/test_sensor.ambr\nindex dbd689fc8f6ce3..b8ad82c7b79951 100644\n--- a/tests/components/swiss_public_transport/snapshots/test_sensor.ambr\n+++ b/tests/components/swiss_public_transport/snapshots/test_sensor.ambr\n@@ -192,7 +192,7 @@\n     'state': '2024-01-06T17:05:00+00:00',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_duration-entry]\n+# name: test_all_entities[sensor.zurich_bern_line-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -204,7 +204,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_duration',\n+    'entity_id': 'sensor.zurich_bern_line',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -214,34 +214,32 @@\n     'name': None,\n     'options': dict({\n     }),\n-    'original_device_class': <SensorDeviceClass.DURATION: 'duration'>,\n+    'original_device_class': None,\n     'original_icon': None,\n-    'original_name': 'Duration',\n+    'original_name': 'Line',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': None,\n-    'unique_id': 'Z\u00fcrich Bern_duration',\n-    'unit_of_measurement': <UnitOfTime.SECONDS: 's'>,\n+    'translation_key': 'line',\n+    'unique_id': 'Z\u00fcrich Bern_line',\n+    'unit_of_measurement': None,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_duration-state]\n+# name: test_all_entities[sensor.zurich_bern_line-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'device_class': 'duration',\n-      'friendly_name': 'Z\u00fcrich Bern Duration',\n-      'unit_of_measurement': <UnitOfTime.SECONDS: 's'>,\n+      'friendly_name': 'Z\u00fcrich Bern Line',\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_duration',\n+    'entity_id': 'sensor.zurich_bern_line',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': '10',\n+    'state': 'T10',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_line-entry]\n+# name: test_all_entities[sensor.zurich_bern_platform-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -253,7 +251,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_line',\n+    'entity_id': 'sensor.zurich_bern_platform',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -265,30 +263,30 @@\n     }),\n     'original_device_class': None,\n     'original_icon': None,\n-    'original_name': 'Line',\n+    'original_name': 'Platform',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': 'line',\n-    'unique_id': 'Z\u00fcrich Bern_line',\n+    'translation_key': 'platform',\n+    'unique_id': 'Z\u00fcrich Bern_platform',\n     'unit_of_measurement': None,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_line-state]\n+# name: test_all_entities[sensor.zurich_bern_platform-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'friendly_name': 'Z\u00fcrich Bern Line',\n+      'friendly_name': 'Z\u00fcrich Bern Platform',\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_line',\n+    'entity_id': 'sensor.zurich_bern_platform',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'T10',\n+    'state': '0',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_platform-entry]\n+# name: test_all_entities[sensor.zurich_bern_transfers-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -300,7 +298,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_platform',\n+    'entity_id': 'sensor.zurich_bern_transfers',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -312,30 +310,30 @@\n     }),\n     'original_device_class': None,\n     'original_icon': None,\n-    'original_name': 'Platform',\n+    'original_name': 'Transfers',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': 'platform',\n-    'unique_id': 'Z\u00fcrich Bern_platform',\n+    'translation_key': 'transfers',\n+    'unique_id': 'Z\u00fcrich Bern_transfers',\n     'unit_of_measurement': None,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_platform-state]\n+# name: test_all_entities[sensor.zurich_bern_transfers-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'friendly_name': 'Z\u00fcrich Bern Platform',\n+      'friendly_name': 'Z\u00fcrich Bern Transfers',\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_platform',\n+    'entity_id': 'sensor.zurich_bern_transfers',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n     'state': '0',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_transfers-entry]\n+# name: test_all_entities[sensor.zurich_bern_trip_duration-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -347,7 +345,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_transfers',\n+    'entity_id': 'sensor.zurich_bern_trip_duration',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -356,29 +354,34 @@\n     }),\n     'name': None,\n     'options': dict({\n+      'sensor.private': dict({\n+        'suggested_unit_of_measurement': <UnitOfTime.HOURS: 'h'>,\n+      }),\n     }),\n-    'original_device_class': None,\n+    'original_device_class': <SensorDeviceClass.DURATION: 'duration'>,\n     'original_icon': None,\n-    'original_name': 'Transfers',\n+    'original_name': 'Trip duration',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': 'transfers',\n-    'unique_id': 'Z\u00fcrich Bern_transfers',\n-    'unit_of_measurement': None,\n+    'translation_key': 'trip_duration',\n+    'unique_id': 'Z\u00fcrich Bern_duration',\n+    'unit_of_measurement': <UnitOfTime.HOURS: 'h'>,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_transfers-state]\n+# name: test_all_entities[sensor.zurich_bern_trip_duration-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'friendly_name': 'Z\u00fcrich Bern Transfers',\n+      'device_class': 'duration',\n+      'friendly_name': 'Z\u00fcrich Bern Trip duration',\n+      'unit_of_measurement': <UnitOfTime.HOURS: 'h'>,\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_transfers',\n+    'entity_id': 'sensor.zurich_bern_trip_duration',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': '0',\n+    'state': '0.003',\n   })\n # ---\ndiff --git a/tests/components/swiss_public_transport/test_sensor.py b/tests/components/swiss_public_transport/test_sensor.py\nindex 4afdd88c9de2f8..6e8327282773e7 100644\n--- a/tests/components/swiss_public_transport/test_sensor.py\n+++ b/tests/components/swiss_public_transport/test_sensor.py\n@@ -83,7 +83,7 @@ async def test_fetching_data(\n         hass.states.get(\"sensor.zurich_bern_departure_2\").state\n         == \"2024-01-06T17:05:00+00:00\"\n     )\n-    assert hass.states.get(\"sensor.zurich_bern_duration\").state == \"10\"\n+    assert hass.states.get(\"sensor.zurich_bern_trip_duration\").state == \"0.003\"\n     assert hass.states.get(\"sensor.zurich_bern_platform\").state == \"0\"\n     assert hass.states.get(\"sensor.zurich_bern_transfers\").state == \"0\"\n     assert hass.states.get(\"sensor.zurich_bern_delay\").state == \"0\"\n", "problem_statement": "Swiss Public Transport: Duration field uses generic name and seconds as default unit\n### The problem\n\nThe entity \"Duration\" has a translatable friendly name defined in the strings.json of the Swiss Public Transport integration:\n\nhttps://github.com/home-assistant/core/blob/fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5/homeassistant/components/swiss_public_transport/strings.json#L67-L68\n\nBut that field does not seem to get used for that name but some generic \"Duration\" field instead. \n\nIn German I have translated this field as \"Fahrzeit\" in Lokalise\n\n![Image](https://github.com/user-attachments/assets/ff44215c-2550-4386-a39a-3681ac47c9a9)\n\nbut I still see \"Dauer\" in the UI:\n\n![Image](https://github.com/user-attachments/assets/9d3c3ca8-1a91-4490-8223-261ed8307709)\n\nAll other sensors have picked up their localized names as they should.\n\n\nIn addtion it would be cool if that field used hours as the unit by default.\nAs a user I can make this change in the entity settings and it's much more useful then:\n\n![Image](https://github.com/user-attachments/assets/8f9da90b-8032-4539-b724-b531c2feda12)\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n_No response_\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nSwiss Public Transport\n\n### Link to integration documentation on our website\n\nhttps://rc.home-assistant.io/integrations/swiss_public_transport\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\nSwiss Public Transport: Duration field uses generic name and seconds as default unit\n### The problem\n\nThe entity \"Duration\" has a translatable friendly name defined in the strings.json of the Swiss Public Transport integration:\n\nhttps://github.com/home-assistant/core/blob/fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5/homeassistant/components/swiss_public_transport/strings.json#L67-L68\n\nBut that field does not seem to get used for that name but some generic \"Duration\" field instead. \n\nIn German I have translated this field as \"Fahrzeit\" in Lokalise\n\n![Image](https://github.com/user-attachments/assets/ff44215c-2550-4386-a39a-3681ac47c9a9)\n\nbut I still see \"Dauer\" in the UI:\n\n![Image](https://github.com/user-attachments/assets/9d3c3ca8-1a91-4490-8223-261ed8307709)\n\nAll other sensors have picked up their localized names as they should.\n\n\nIn addtion it would be cool if that field used hours as the unit by default.\nAs a user I can make this change in the entity settings and it's much more useful then:\n\n![Image](https://github.com/user-attachments/assets/8f9da90b-8032-4539-b724-b531c2feda12)\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n_No response_\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nSwiss Public Transport\n\n### Link to integration documentation on our website\n\nhttps://rc.home-assistant.io/integrations/swiss_public_transport\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @fabaff, @miaucl, mind taking a look at this issue as it has been labeled with an integration (`swiss_public_transport`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1471) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `swiss_public_transport` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign swiss_public_transport` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[swiss_public_transport documentation](https://www.home-assistant.io/integrations/swiss_public_transport)\n[swiss_public_transport source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/swiss_public_transport)\n<sub><sup>(message by IssueLinks)</sup></sub>\n@NoRi2909 Good spot, the translation key was missing for `Duration`. But regarding the duration measurement unit, The raw data arriving is in seconds and I do not want to opinionate and convert in home assistant, this is usually up to the user.\n\nHey there @fabaff, @miaucl, mind taking a look at this issue as it has been labeled with an integration (`swiss_public_transport`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1471) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `swiss_public_transport` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign swiss_public_transport` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[swiss_public_transport documentation](https://www.home-assistant.io/integrations/swiss_public_transport)\n[swiss_public_transport source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/swiss_public_transport)\n<sub><sup>(message by IssueLinks)</sup></sub>\n@NoRi2909 Good spot, the translation key was missing for `Duration`. But regarding the duration measurement unit, The raw data arriving is in seconds and I do not want to opinionate and convert in home assistant, this is usually up to the user.", "created_at": "2025-01-31T09:07:10Z"}
{"repo": "home-assistant/core", "pull_number": 136980, "instance_id": "home-assistant__core-136980", "issue_numbers": ["136959"], "base_commit": "fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5", "patch": "diff --git a/homeassistant/components/onedrive/backup.py b/homeassistant/components/onedrive/backup.py\nindex 94d60bc6398125..7f4bd5a07383cc 100644\n--- a/homeassistant/components/onedrive/backup.py\n+++ b/homeassistant/components/onedrive/backup.py\n@@ -2,6 +2,7 @@\n \n from __future__ import annotations\n \n+import asyncio\n from collections.abc import AsyncIterator, Callable, Coroutine\n from functools import wraps\n import html\n@@ -9,7 +10,7 @@\n import logging\n from typing import Any, Concatenate, cast\n \n-from httpx import Response\n+from httpx import Response, TimeoutException\n from kiota_abstractions.api_error import APIError\n from kiota_abstractions.authentication import AnonymousAuthenticationProvider\n from kiota_abstractions.headers_collection import HeadersCollection\n@@ -42,6 +43,7 @@\n \n _LOGGER = logging.getLogger(__name__)\n UPLOAD_CHUNK_SIZE = 16 * 320 * 1024  # 5.2MB\n+MAX_RETRIES = 5\n \n \n async def async_get_backup_agents(\n@@ -96,7 +98,7 @@ async def wrapper(\n             )\n             _LOGGER.debug(\"Full error: %s\", err, exc_info=True)\n             raise BackupAgentError(\"Backup operation failed\") from err\n-        except TimeoutError as err:\n+        except TimeoutException as err:\n             _LOGGER.error(\n                 \"Error during backup in %s: Timeout\",\n                 func.__name__,\n@@ -268,6 +270,7 @@ async def async_upload(\n         start = 0\n         buffer: list[bytes] = []\n         buffer_size = 0\n+        retries = 0\n \n         async for chunk in stream:\n             buffer.append(chunk)\n@@ -279,11 +282,28 @@ async def async_upload(\n                     buffer_size > UPLOAD_CHUNK_SIZE\n                 ):  # Loop in case the buffer is >= UPLOAD_CHUNK_SIZE * 2\n                     slice_start = uploaded_chunks * UPLOAD_CHUNK_SIZE\n-                    await async_upload(\n-                        start,\n-                        start + UPLOAD_CHUNK_SIZE - 1,\n-                        chunk_data[slice_start : slice_start + UPLOAD_CHUNK_SIZE],\n-                    )\n+                    try:\n+                        await async_upload(\n+                            start,\n+                            start + UPLOAD_CHUNK_SIZE - 1,\n+                            chunk_data[slice_start : slice_start + UPLOAD_CHUNK_SIZE],\n+                        )\n+                    except APIError as err:\n+                        if (\n+                            err.response_status_code and err.response_status_code < 500\n+                        ):  # no retry on 4xx errors\n+                            raise\n+                        if retries < MAX_RETRIES:\n+                            await asyncio.sleep(2**retries)\n+                            retries += 1\n+                            continue\n+                        raise\n+                    except TimeoutException:\n+                        if retries < MAX_RETRIES:\n+                            retries += 1\n+                            continue\n+                        raise\n+                    retries = 0\n                     start += UPLOAD_CHUNK_SIZE\n                     uploaded_chunks += 1\n                     buffer_size -= UPLOAD_CHUNK_SIZE\n", "test_patch": "diff --git a/tests/components/onedrive/conftest.py b/tests/components/onedrive/conftest.py\nindex 65142217017431..649966a7828978 100644\n--- a/tests/components/onedrive/conftest.py\n+++ b/tests/components/onedrive/conftest.py\n@@ -176,3 +176,10 @@ def mock_instance_id() -> Generator[AsyncMock]:\n         return_value=\"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0\",\n     ):\n         yield\n+\n+\n+@pytest.fixture(autouse=True)\n+def mock_asyncio_sleep() -> Generator[AsyncMock]:\n+    \"\"\"Mock asyncio.sleep.\"\"\"\n+    with patch(\"homeassistant.components.onedrive.backup.asyncio.sleep\", AsyncMock()):\n+        yield\ndiff --git a/tests/components/onedrive/test_backup.py b/tests/components/onedrive/test_backup.py\nindex 3492202d3feb08..162ecb7d92ae74 100644\n--- a/tests/components/onedrive/test_backup.py\n+++ b/tests/components/onedrive/test_backup.py\n@@ -8,8 +8,10 @@\n from json import dumps\n from unittest.mock import Mock, patch\n \n+from httpx import TimeoutException\n from kiota_abstractions.api_error import APIError\n from msgraph.generated.models.drive_item import DriveItem\n+from msgraph_core.models import LargeFileUploadSession\n import pytest\n \n from homeassistant.components.backup import DOMAIN as BACKUP_DOMAIN, AgentBackup\n@@ -255,6 +257,140 @@ async def test_broken_upload_session(\n     assert \"Failed to start backup upload\" in caplog.text\n \n \n+@pytest.mark.parametrize(\n+    \"side_effect\",\n+    [\n+        APIError(response_status_code=500),\n+        TimeoutException(\"Timeout\"),\n+    ],\n+)\n+async def test_agents_upload_errors_retried(\n+    hass_client: ClientSessionGenerator,\n+    caplog: pytest.LogCaptureFixture,\n+    mock_drive_items: MagicMock,\n+    mock_config_entry: MockConfigEntry,\n+    mock_adapter: MagicMock,\n+    side_effect: Exception,\n+) -> None:\n+    \"\"\"Test agent upload backup.\"\"\"\n+    client = await hass_client()\n+    test_backup = AgentBackup.from_dict(BACKUP_METADATA)\n+\n+    mock_adapter.send_async.side_effect = [\n+        side_effect,\n+        LargeFileUploadSession(next_expected_ranges=[\"2-\"]),\n+        LargeFileUploadSession(next_expected_ranges=[\"2-\"]),\n+    ]\n+\n+    with (\n+        patch(\n+            \"homeassistant.components.backup.manager.BackupManager.async_get_backup\",\n+        ) as fetch_backup,\n+        patch(\n+            \"homeassistant.components.backup.manager.read_backup\",\n+            return_value=test_backup,\n+        ),\n+        patch(\"pathlib.Path.open\") as mocked_open,\n+        patch(\"homeassistant.components.onedrive.backup.UPLOAD_CHUNK_SIZE\", 3),\n+    ):\n+        mocked_open.return_value.read = Mock(side_effect=[b\"test\", b\"\"])\n+        fetch_backup.return_value = test_backup\n+        resp = await client.post(\n+            f\"/api/backup/upload?agent_id={DOMAIN}.{mock_config_entry.unique_id}\",\n+            data={\"file\": StringIO(\"test\")},\n+        )\n+\n+    assert resp.status == 201\n+    assert mock_adapter.send_async.call_count == 3\n+    assert f\"Uploading backup {test_backup.backup_id}\" in caplog.text\n+    mock_drive_items.patch.assert_called_once()\n+\n+\n+async def test_agents_upload_4xx_errors_not_retried(\n+    hass_client: ClientSessionGenerator,\n+    caplog: pytest.LogCaptureFixture,\n+    mock_drive_items: MagicMock,\n+    mock_config_entry: MockConfigEntry,\n+    mock_adapter: MagicMock,\n+) -> None:\n+    \"\"\"Test agent upload backup.\"\"\"\n+    client = await hass_client()\n+    test_backup = AgentBackup.from_dict(BACKUP_METADATA)\n+\n+    mock_adapter.send_async.side_effect = APIError(response_status_code=404)\n+\n+    with (\n+        patch(\n+            \"homeassistant.components.backup.manager.BackupManager.async_get_backup\",\n+        ) as fetch_backup,\n+        patch(\n+            \"homeassistant.components.backup.manager.read_backup\",\n+            return_value=test_backup,\n+        ),\n+        patch(\"pathlib.Path.open\") as mocked_open,\n+        patch(\"homeassistant.components.onedrive.backup.UPLOAD_CHUNK_SIZE\", 3),\n+    ):\n+        mocked_open.return_value.read = Mock(side_effect=[b\"test\", b\"\"])\n+        fetch_backup.return_value = test_backup\n+        resp = await client.post(\n+            f\"/api/backup/upload?agent_id={DOMAIN}.{mock_config_entry.unique_id}\",\n+            data={\"file\": StringIO(\"test\")},\n+        )\n+\n+    assert resp.status == 201\n+    assert mock_adapter.send_async.call_count == 1\n+    assert f\"Uploading backup {test_backup.backup_id}\" in caplog.text\n+    assert mock_drive_items.patch.call_count == 0\n+    assert \"Backup operation failed\" in caplog.text\n+\n+\n+@pytest.mark.parametrize(\n+    (\"side_effect\", \"error\"),\n+    [\n+        (APIError(response_status_code=500), \"Backup operation failed\"),\n+        (TimeoutException(\"Timeout\"), \"Backup operation timed out\"),\n+    ],\n+)\n+async def test_agents_upload_fails_after_max_retries(\n+    hass_client: ClientSessionGenerator,\n+    caplog: pytest.LogCaptureFixture,\n+    mock_drive_items: MagicMock,\n+    mock_config_entry: MockConfigEntry,\n+    mock_adapter: MagicMock,\n+    side_effect: Exception,\n+    error: str,\n+) -> None:\n+    \"\"\"Test agent upload backup.\"\"\"\n+    client = await hass_client()\n+    test_backup = AgentBackup.from_dict(BACKUP_METADATA)\n+\n+    mock_adapter.send_async.side_effect = side_effect\n+\n+    with (\n+        patch(\n+            \"homeassistant.components.backup.manager.BackupManager.async_get_backup\",\n+        ) as fetch_backup,\n+        patch(\n+            \"homeassistant.components.backup.manager.read_backup\",\n+            return_value=test_backup,\n+        ),\n+        patch(\"pathlib.Path.open\") as mocked_open,\n+        patch(\"homeassistant.components.onedrive.backup.UPLOAD_CHUNK_SIZE\", 3),\n+    ):\n+        mocked_open.return_value.read = Mock(side_effect=[b\"test\", b\"\"])\n+        fetch_backup.return_value = test_backup\n+        resp = await client.post(\n+            f\"/api/backup/upload?agent_id={DOMAIN}.{mock_config_entry.unique_id}\",\n+            data={\"file\": StringIO(\"test\")},\n+        )\n+\n+    assert resp.status == 201\n+    assert mock_adapter.send_async.call_count == 6\n+    assert f\"Uploading backup {test_backup.backup_id}\" in caplog.text\n+    assert mock_drive_items.patch.call_count == 0\n+    assert error in caplog.text\n+\n+\n async def test_agents_download(\n     hass_client: ClientSessionGenerator,\n     mock_drive_items: MagicMock,\n@@ -282,7 +418,7 @@ async def test_agents_download(\n             APIError(response_status_code=500),\n             \"Backup operation failed\",\n         ),\n-        (TimeoutError(), \"Backup operation timed out\"),\n+        (TimeoutException(\"Timeout\"), \"Backup operation timed out\"),\n     ],\n )\n async def test_delete_error(\n", "problem_statement": "2025.2.0b2 One Drive Automatic backup fails\n### The problem\n\nInitiated an automatic backup One Drive failed.  Local, local network and Google Drive succeeded \nRepeated 10 minutes later same failure. I'm able to access One Drive directly on my PC  \n\n![Image](https://github.com/user-attachments/assets/2e9ccd95-ded7-4f8b-b10d-ba14c2032184)\n\n### What version of Home Assistant Core has the issue?\n\n2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n2025.2.0b1\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nBackup\n\n### Link to integration documentation on our website\n\n_No response_\n\n### Diagnostics information\n\n```\nLogger: homeassistant.components.backup\nSource: components/backup/manager.py:512\nintegration: Backup ([documentation](https://rc.home-assistant.io/integrations/backup), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+backup%22))\nFirst occurred: 2:32:18 PM (1 occurrences)\nLast logged: 2:32:18 PM\n\nUnexpected error for onedrive.D378A3F5743D8717:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 101, in map_httpcore_exceptions\n    yield\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 394, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py\", line 256, in handle_async_request\n    raise exc from None\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py\", line 236, in handle_async_request\n    response = await connection.handle_async_request(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        pool_request.request\n        ^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py\", line 103, in handle_async_request\n    return await self._connection.handle_async_request(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 136, in handle_async_request\n    raise exc\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 106, in handle_async_request\n    ) = await self._receive_response_headers(**kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 177, in _receive_response_headers\n    event = await self._receive_event(timeout=timeout)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 217, in _receive_event\n    data = await self._network_stream.read(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        self.READ_NUM_BYTES, timeout=timeout\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_backends/anyio.py\", line 32, in read\n    with map_exceptions(exc_map):\n         ~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/usr/local/lib/python3.13/contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n    raise to_exc(exc) from exc\nhttpcore.ReadTimeout\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/src/homeassistant/homeassistant/components/backup/manager.py\", line 512, in upload_backup_to_agent\n    await self.backup_agents[agent_id].async_upload_backup(\n    ...<2 lines>...\n    )\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 87, in wrapper\n    return await func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 172, in async_upload_backup\n    await self._upload_file(\n        upload_session.upload_url, await open_stream(), backup.size\n    )\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 282, in _upload_file\n    await async_upload(\n    ...<3 lines>...\n    )\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 264, in async_upload\n    result = await adapter.send_async(info, LargeFileUploadSession, {})\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/kiota_http/httpx_request_adapter.py\", line 186, in send_async\n    response = await self.get_http_response_message(request_info, parent_span)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/kiota_http/httpx_request_adapter.py\", line 602, in get_http_response_message\n    resp = await self._http_client.send(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1629, in send\n    response = await self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<4 lines>...\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1657, in _send_handling_auth\n    response = await self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1694, in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1730, in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 393, in handle_async_request\n    with map_httpcore_exceptions():\n         ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/usr/local/lib/python3.13/contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 118, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.ReadTimeout\n```\n\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @home-assistant/core, mind taking a look at this issue as it has been labeled with an integration (`backup`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L183) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `backup` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign backup` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[backup documentation](https://www.home-assistant.io/integrations/backup)\n[backup source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/backup)\n<sub><sup>(message by IssueLinks)</sup></sub>\nJust want to chime in that I get the same error. With 2025.2.0b1 I could not connect to OneDrive. With b2 it is possible to link it.\n\n```\nLogger: homeassistant.components.onedrive.backup\nSource: components/onedrive/backup.py:91\nintegration: OneDrive (documentation, issues)\nFirst occurred: 22:08:57 (1 occurrences)\nLast logged: 22:08:57\n\nError during backup in async_upload_backup: Status 400, message None\n```\n\nAnd\n```\nLogger: homeassistant.components.backup\nSource: components/backup/manager.py:531\nintegration: Backup (documentation, issues)\nFirst occurred: 22:08:57 (1 occurrences)\nLast logged: 22:08:57\n\nUpload failed for onedrive.ea093e654287a17c: Backup operation failed\n```\n\nHmm, just checked my OneDrive and the Folders /Apps/Home Assistant/backups_slug/ are created and I even see a .tar file in the folder.\n\nThe state inside Home Assistant still says the upload failed though.\n\nTried an encrypted and unencrypted OneDrive backup. Both give the same error, and both upload the file just fine.\nJust tried the same thing again; Initiated an automated backup and the upload to One Drive succeeded. \nAppears to be an intermittent problem\n\nHey there @zweckj, mind taking a look at this issue as it has been labeled with an integration (`onedrive`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1076) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `onedrive` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign onedrive` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[onedrive documentation](https://www.home-assistant.io/integrations/onedrive)\n[onedrive source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/onedrive)\n<sub><sup>(message by IssueLinks)</sup></sub>", "created_at": "2025-01-31T08:31:24Z"}
{"repo": "home-assistant/core", "pull_number": 136949, "instance_id": "home-assistant__core-136949", "issue_numbers": ["134861"], "base_commit": "b12598d9633e16af9d2330b40db304dec13b2874", "patch": "diff --git a/homeassistant/components/home_connect/coordinator.py b/homeassistant/components/home_connect/coordinator.py\nindex 2c70d74150e35d..29bd961220ec74 100644\n--- a/homeassistant/components/home_connect/coordinator.py\n+++ b/homeassistant/components/home_connect/coordinator.py\n@@ -25,7 +25,7 @@\n     HomeConnectError,\n     HomeConnectRequestError,\n )\n-from aiohomeconnect.model.program import EnumerateAvailableProgram\n+from aiohomeconnect.model.program import EnumerateProgram\n from propcache.api import cached_property\n \n from homeassistant.config_entries import ConfigEntry\n@@ -48,7 +48,7 @@ class HomeConnectApplianceData:\n \n     events: dict[EventKey, Event] = field(default_factory=dict)\n     info: HomeAppliance\n-    programs: list[EnumerateAvailableProgram] = field(default_factory=list)\n+    programs: list[EnumerateProgram] = field(default_factory=list)\n     settings: dict[SettingKey, GetSetting]\n     status: dict[StatusKey, Status]\n \n@@ -243,9 +243,7 @@ async def _async_update_data(self) -> dict[str, HomeConnectApplianceData]:\n             ):\n                 try:\n                     appliance_data.programs.extend(\n-                        (\n-                            await self.client.get_available_programs(appliance.ha_id)\n-                        ).programs\n+                        (await self.client.get_all_programs(appliance.ha_id)).programs\n                     )\n                 except HomeConnectError as error:\n                     _LOGGER.debug(\ndiff --git a/homeassistant/components/home_connect/switch.py b/homeassistant/components/home_connect/switch.py\nindex c3a0858e0bb1b2..521252ccc2fa00 100644\n--- a/homeassistant/components/home_connect/switch.py\n+++ b/homeassistant/components/home_connect/switch.py\n@@ -5,7 +5,7 @@\n \n from aiohomeconnect.model import EventKey, ProgramKey, SettingKey\n from aiohomeconnect.model.error import HomeConnectError\n-from aiohomeconnect.model.program import EnumerateAvailableProgram\n+from aiohomeconnect.model.program import EnumerateProgram\n \n from homeassistant.components.automation import automations_with_entity\n from homeassistant.components.script import scripts_with_entity\n@@ -184,7 +184,7 @@ def __init__(\n         self,\n         coordinator: HomeConnectCoordinator,\n         appliance: HomeConnectApplianceData,\n-        program: EnumerateAvailableProgram,\n+        program: EnumerateProgram,\n     ) -> None:\n         \"\"\"Initialize the entity.\"\"\"\n         desc = \" \".join([\"Program\", program.key.split(\".\")[-1]])\n", "test_patch": "diff --git a/tests/components/home_connect/conftest.py b/tests/components/home_connect/conftest.py\nindex af039f04c03175..ae98c69d242931 100644\n--- a/tests/components/home_connect/conftest.py\n+++ b/tests/components/home_connect/conftest.py\n@@ -9,9 +9,9 @@\n \n from aiohomeconnect.client import Client as HomeConnectClient\n from aiohomeconnect.model import (\n-    ArrayOfAvailablePrograms,\n     ArrayOfEvents,\n     ArrayOfHomeAppliances,\n+    ArrayOfPrograms,\n     ArrayOfSettings,\n     ArrayOfStatus,\n     Event,\n@@ -37,9 +37,7 @@\n MOCK_APPLIANCES = ArrayOfHomeAppliances.from_dict(\n     load_json_object_fixture(\"home_connect/appliances.json\")[\"data\"]\n )\n-MOCK_PROGRAMS: dict[str, Any] = load_json_object_fixture(\n-    \"home_connect/programs-available.json\"\n-)\n+MOCK_PROGRAMS: dict[str, Any] = load_json_object_fixture(\"home_connect/programs.json\")\n MOCK_SETTINGS: dict[str, Any] = load_json_object_fixture(\"home_connect/settings.json\")\n MOCK_STATUS = ArrayOfStatus.from_dict(\n     load_json_object_fixture(\"home_connect/status.json\")[\"data\"]\n@@ -219,8 +217,8 @@ async def set_key_value_side_effect(ha_id: str, *_, **kwargs) -> None:\n     return set_key_value_side_effect\n \n \n-async def _get_available_programs_side_effect(ha_id: str) -> ArrayOfAvailablePrograms:\n-    \"\"\"Get available programs.\"\"\"\n+async def _get_all_programs_side_effect(ha_id: str) -> ArrayOfPrograms:\n+    \"\"\"Get all programs.\"\"\"\n     appliance_type = next(\n         appliance\n         for appliance in MOCK_APPLIANCES.homeappliances\n@@ -229,7 +227,7 @@ async def _get_available_programs_side_effect(ha_id: str) -> ArrayOfAvailablePro\n     if appliance_type not in MOCK_PROGRAMS:\n         raise HomeConnectApiError(\"error.key\", \"error description\")\n \n-    return ArrayOfAvailablePrograms.from_dict(MOCK_PROGRAMS[appliance_type][\"data\"])\n+    return ArrayOfPrograms.from_dict(MOCK_PROGRAMS[appliance_type][\"data\"])\n \n \n async def _get_settings_side_effect(ha_id: str) -> ArrayOfSettings:\n@@ -290,9 +288,7 @@ async def stream_all_events() -> AsyncGenerator[EventMessage]:\n     )\n     mock.get_settings = AsyncMock(side_effect=_get_settings_side_effect)\n     mock.get_status = AsyncMock(return_value=copy.deepcopy(MOCK_STATUS))\n-    mock.get_available_programs = AsyncMock(\n-        side_effect=_get_available_programs_side_effect\n-    )\n+    mock.get_all_programs = AsyncMock(side_effect=_get_all_programs_side_effect)\n     mock.put_command = AsyncMock()\n \n     mock.side_effect = mock\n@@ -323,7 +319,6 @@ async def stream_all_events() -> AsyncGenerator[EventMessage]:\n \n     mock.start_program = AsyncMock(side_effect=exception)\n     mock.stop_program = AsyncMock(side_effect=exception)\n-    mock.get_available_programs = AsyncMock(side_effect=exception)\n     mock.set_selected_program = AsyncMock(side_effect=exception)\n     mock.set_active_program_option = AsyncMock(side_effect=exception)\n     mock.set_selected_program_option = AsyncMock(side_effect=exception)\n@@ -331,7 +326,7 @@ async def stream_all_events() -> AsyncGenerator[EventMessage]:\n     mock.get_settings = AsyncMock(side_effect=exception)\n     mock.get_setting = AsyncMock(side_effect=exception)\n     mock.get_status = AsyncMock(side_effect=exception)\n-    mock.get_available_programs = AsyncMock(side_effect=exception)\n+    mock.get_all_programs = AsyncMock(side_effect=exception)\n     mock.put_command = AsyncMock(side_effect=exception)\n \n     return mock\ndiff --git a/tests/components/home_connect/fixtures/programs-available.json b/tests/components/home_connect/fixtures/programs.json\nsimilarity index 100%\nrename from tests/components/home_connect/fixtures/programs-available.json\nrename to tests/components/home_connect/fixtures/programs.json\ndiff --git a/tests/components/home_connect/test_select.py b/tests/components/home_connect/test_select.py\nindex 6ebd37266cd4ef..a0cdd15bf318db 100644\n--- a/tests/components/home_connect/test_select.py\n+++ b/tests/components/home_connect/test_select.py\n@@ -4,8 +4,8 @@\n from unittest.mock import MagicMock\n \n from aiohomeconnect.model import (\n-    ArrayOfAvailablePrograms,\n     ArrayOfEvents,\n+    ArrayOfPrograms,\n     Event,\n     EventKey,\n     EventMessage,\n@@ -13,7 +13,7 @@\n     ProgramKey,\n )\n from aiohomeconnect.model.error import HomeConnectError\n-from aiohomeconnect.model.program import EnumerateAvailableProgram\n+from aiohomeconnect.model.program import EnumerateProgram\n import pytest\n \n from homeassistant.components.select import (\n@@ -61,14 +61,14 @@ async def test_filter_unknown_programs(\n     entity_registry: er.EntityRegistry,\n ) -> None:\n     \"\"\"Test select that only known programs are shown.\"\"\"\n-    client.get_available_programs.side_effect = None\n-    client.get_available_programs.return_value = ArrayOfAvailablePrograms(\n+    client.get_all_programs.side_effect = None\n+    client.get_all_programs.return_value = ArrayOfPrograms(\n         [\n-            EnumerateAvailableProgram(\n+            EnumerateProgram(\n                 key=ProgramKey.DISHCARE_DISHWASHER_ECO_50,\n                 raw_key=ProgramKey.DISHCARE_DISHWASHER_ECO_50.value,\n             ),\n-            EnumerateAvailableProgram(\n+            EnumerateProgram(\n                 key=ProgramKey.UNKNOWN,\n                 raw_key=\"an unknown program\",\n             ),\n@@ -202,16 +202,14 @@ async def test_select_exception_handling(\n     client_with_exception: MagicMock,\n ) -> None:\n     \"\"\"Test exception handling.\"\"\"\n-    client_with_exception.get_available_programs.side_effect = None\n-    client_with_exception.get_available_programs.return_value = (\n-        ArrayOfAvailablePrograms(\n-            [\n-                EnumerateAvailableProgram(\n-                    key=ProgramKey.DISHCARE_DISHWASHER_ECO_50,\n-                    raw_key=ProgramKey.DISHCARE_DISHWASHER_ECO_50.value,\n-                )\n-            ]\n-        )\n+    client_with_exception.get_all_programs.side_effect = None\n+    client_with_exception.get_all_programs.return_value = ArrayOfPrograms(\n+        [\n+            EnumerateProgram(\n+                key=ProgramKey.DISHCARE_DISHWASHER_ECO_50,\n+                raw_key=ProgramKey.DISHCARE_DISHWASHER_ECO_50.value,\n+            )\n+        ]\n     )\n \n     assert config_entry.state is ConfigEntryState.NOT_LOADED\ndiff --git a/tests/components/home_connect/test_switch.py b/tests/components/home_connect/test_switch.py\nindex 10d393423be831..4d6b59eddd9983 100644\n--- a/tests/components/home_connect/test_switch.py\n+++ b/tests/components/home_connect/test_switch.py\n@@ -15,10 +15,7 @@\n )\n from aiohomeconnect.model.error import HomeConnectError\n from aiohomeconnect.model.event import ArrayOfEvents, EventType\n-from aiohomeconnect.model.program import (\n-    ArrayOfAvailablePrograms,\n-    EnumerateAvailableProgram,\n-)\n+from aiohomeconnect.model.program import ArrayOfPrograms, EnumerateProgram\n from aiohomeconnect.model.setting import SettingConstraints\n import pytest\n \n@@ -250,16 +247,14 @@ async def test_switch_exception_handling(\n     client_with_exception: MagicMock,\n ) -> None:\n     \"\"\"Test exception handling.\"\"\"\n-    client_with_exception.get_available_programs.side_effect = None\n-    client_with_exception.get_available_programs.return_value = (\n-        ArrayOfAvailablePrograms(\n-            [\n-                EnumerateAvailableProgram(\n-                    key=ProgramKey.DISHCARE_DISHWASHER_ECO_50,\n-                    raw_key=ProgramKey.DISHCARE_DISHWASHER_ECO_50.value,\n-                )\n-            ]\n-        )\n+    client_with_exception.get_all_programs.side_effect = None\n+    client_with_exception.get_all_programs.return_value = ArrayOfPrograms(\n+        [\n+            EnumerateProgram(\n+                key=ProgramKey.DISHCARE_DISHWASHER_ECO_50,\n+                raw_key=ProgramKey.DISHCARE_DISHWASHER_ECO_50.value,\n+            )\n+        ]\n     )\n     client_with_exception.get_settings.side_effect = None\n     client_with_exception.get_settings.return_value = ArrayOfSettings(\n", "problem_statement": "If the integration is reloaded while running a program, the running program is the only program available at select entities\n### The problem\n\nAfter the upgrade to 2025.1 at first I could see the program selected on the dishwasher in \"selected program\"\r\nI did some test where I selected pre_rinse at the dishwasher and copied the value of the \"selected program\" to \"Active program\" in an automation. Pre rinse on the machine started.\r\nSince then only pre_rinse is available in home connect. It doesn't show the program selected on the dishwasher anymore.\r\nExecuting the automation:\r\n\r\n\r\naction: select.select_option\r\ndata:\r\n  option: dishcare_dishwasher_program_auto3\r\ntarget:\r\n  entity_id: select.dishwasher_active_program\r\n\r\ngives:\r\n\r\n> Error running action\r\n\r\nOption dishcare_dishwasher_program_auto3 is not valid for entity select.dishwasher_active_program, valid options are: dishcare_dishwasher_program_pre_rinse\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.1.0\n\n### What was the last working version of Home Assistant Core?\n\n_No response_\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nHome Connect\n\n### Link to integration documentation on our website\n\nhttps://www.home-assistant.io/integrations/home_connect/\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\naction: select.select_option\r\ndata:\r\n  option: dishcare_dishwasher_program_auto3\r\ntarget:\r\n  entity_id: select.dishwasher_active_program\n```\n\n\n### Anything in the logs that might be useful for us?\n\n_No response_\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @davidmstraub, @diegorro98, mind taking a look at this issue as it has been labeled with an integration (`home_connect`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L626) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `home_connect` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign home_connect` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[home_connect documentation](https://www.home-assistant.io/integrations/home_connect)\n[home_connect source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/home_connect)\n<sub><sup>(message by IssueLinks)</sup></sub>\nHi!\r\nIf I understand correctly, your problem is that after starting the \"pre-rinse\" program, then only \"pre-rinse\" is available, right?\r\nDo you know if the integration was reloaded or Home Assistant was restarted while the dishwasher was running the program?\nYes, pre-rinse was started by copying from  \"selected program\" to \"active program\".\r\nI can't recall if home-assistant was restarted while running the program. I didn't let the program finish though.\r\nIt was restarted a few times later.\r\nStrange just did a restart and it sees all the programs.\r\nCan it be that when home assistant is restarted with the dishwasher powered, but not on home assistant only knows the last program.\r\nSo for home assistant to see all programs the dishwasher needs be switched on when home assistant is restarted.\r\n\nSome more testing.\r\nThe dishwasher defaults to eco. That is not visible in \"selected programs\". It seems selected programs is only filled when I change from the default value when switching on the dishwasher. So switching to auto3 is visible. When switching back to eco also is visible. So making eco work I have to select another program and than eco.\nOkey, so these are to dev-known problems:\r\n\r\n- If the appliance (in your case, the diswasher) is running a program while Home Assistant is restarting or the integration is being reload, the only program available is the program that is currently running.\r\n  Why does this happen? API does return that, maybe it does make sense because we ask to the API what are the available programs, and it is kind of logical that the only program available while the program is running is the program that is currently running\r\n  I would like to fix that once we have changed the library we depend-on right now, which is in the current works\r\n\r\n- Currently we don't fetch which program is selected at the start, we let the API notify us about that. We can ask that to the API at the start, sure, but after the library change\n@home-assistant rename If the integration is reloaded while running a program, the running program is the only program available at select entities", "created_at": "2025-01-30T19:46:06Z"}
{"repo": "home-assistant/core", "pull_number": 136919, "instance_id": "home-assistant__core-136919", "issue_numbers": ["135737"], "base_commit": "5dd147e83b3f02e7da75c33513760967b51850b9", "patch": "diff --git a/homeassistant/components/youless/sensor.py b/homeassistant/components/youless/sensor.py\nindex 3afb215ed5f5a2..db8244c0b0662c 100644\n--- a/homeassistant/components/youless/sensor.py\n+++ b/homeassistant/components/youless/sensor.py\n@@ -36,7 +36,7 @@ class YouLessSensorEntityDescription(SensorEntityDescription):\n     \"\"\"Describes a YouLess sensor entity.\"\"\"\n \n     device_group: str\n-    value_func: Callable[[YoulessAPI], float | None]\n+    value_func: Callable[[YoulessAPI], float | None | str]\n \n \n SENSOR_TYPES: tuple[YouLessSensorEntityDescription, ...] = (\n@@ -212,6 +212,38 @@ class YouLessSensorEntityDescription(SensorEntityDescription):\n             lambda device: device.phase3.current.value if device.phase1 else None\n         ),\n     ),\n+    YouLessSensorEntityDescription(\n+        key=\"tariff\",\n+        device_group=\"power\",\n+        translation_key=\"active_tariff\",\n+        device_class=SensorDeviceClass.ENUM,\n+        options=[\"1\", \"2\"],\n+        value_func=(\n+            lambda device: str(device.current_tariff) if device.current_tariff else None\n+        ),\n+    ),\n+    YouLessSensorEntityDescription(\n+        key=\"average_peak\",\n+        device_group=\"power\",\n+        translation_key=\"average_peak\",\n+        device_class=SensorDeviceClass.POWER,\n+        state_class=SensorStateClass.MEASUREMENT,\n+        native_unit_of_measurement=UnitOfPower.WATT,\n+        value_func=(\n+            lambda device: device.average_power.value if device.average_power else None\n+        ),\n+    ),\n+    YouLessSensorEntityDescription(\n+        key=\"month_peak\",\n+        device_group=\"power\",\n+        translation_key=\"month_peak\",\n+        device_class=SensorDeviceClass.POWER,\n+        state_class=SensorStateClass.MEASUREMENT,\n+        native_unit_of_measurement=UnitOfPower.WATT,\n+        value_func=(\n+            lambda device: device.peak_power.value if device.peak_power else None\n+        ),\n+    ),\n     YouLessSensorEntityDescription(\n         key=\"delivery_low\",\n         device_group=\"delivery\",\ndiff --git a/homeassistant/components/youless/strings.json b/homeassistant/components/youless/strings.json\nindex 8a3f6cb5d8b4f3..c735e2b2ff2e55 100644\n--- a/homeassistant/components/youless/strings.json\n+++ b/homeassistant/components/youless/strings.json\n@@ -52,6 +52,9 @@\n       \"active_current_phase_a\": {\n         \"name\": \"Current phase {phase}\"\n       },\n+      \"active_tariff\": {\n+        \"name\": \"Tariff\"\n+      },\n       \"total_energy_import_tariff_kwh\": {\n         \"name\": \"Energy import tariff {tariff}\"\n       },\n@@ -66,6 +69,12 @@\n       },\n       \"active_s0_w\": {\n         \"name\": \"Current usage\"\n+      },\n+      \"average_peak\": {\n+        \"name\": \"Average peak\"\n+      },\n+      \"month_peak\": {\n+        \"name\": \"Month peak\"\n       }\n     }\n   }\n", "test_patch": "diff --git a/tests/components/youless/__init__.py b/tests/components/youless/__init__.py\nindex 8770a7e2dc8fe0..03db24cb7f76e0 100644\n--- a/tests/components/youless/__init__.py\n+++ b/tests/components/youless/__init__.py\n@@ -25,6 +25,11 @@ async def init_component(hass: HomeAssistant) -> MockConfigEntry:\n             json=load_json_array_fixture(\"enologic.json\", youless.DOMAIN),\n             headers={\"Content-Type\": \"application/json\"},\n         )\n+        mock.get(\n+            \"http://1.1.1.1/f\",\n+            json=load_json_object_fixture(\"phase.json\", youless.DOMAIN),\n+            headers={\"Content-Type\": \"application/json\"},\n+        )\n \n         entry = MockConfigEntry(\n             domain=youless.DOMAIN,\ndiff --git a/tests/components/youless/fixtures/device.json b/tests/components/youless/fixtures/device.json\nindex 7d089851923bca..82d07dba739a04 100644\n--- a/tests/components/youless/fixtures/device.json\n+++ b/tests/components/youless/fixtures/device.json\n@@ -1,5 +1,5 @@\n {\n   \"model\": \"LS120\",\n-  \"fw\": \"1.4.2-EL\",\n+  \"fw\": \"1.5.1-EL\",\n   \"mac\": \"de2:2d2:3d23\"\n }\ndiff --git a/tests/components/youless/fixtures/phase.json b/tests/components/youless/fixtures/phase.json\nnew file mode 100644\nindex 00000000000000..8a5aa3215ef8f6\n--- /dev/null\n+++ b/tests/components/youless/fixtures/phase.json\n@@ -0,0 +1,15 @@\n+{\n+  \"tr\": 1,\n+  \"i1\": 0.123,\n+  \"v1\": 240,\n+  \"l1\": 462,\n+  \"v2\": 240,\n+  \"l2\": 230,\n+  \"i2\": 0.123,\n+  \"v3\": 240,\n+  \"l3\": 230,\n+  \"i3\": 0.123,\n+  \"pp\": 1200,\n+  \"pts\": 2501301621,\n+  \"pa\": 400\n+}\ndiff --git a/tests/components/youless/snapshots/test_sensor.ambr b/tests/components/youless/snapshots/test_sensor.ambr\nindex 0647d854d2a806..9e79b5b9b5ec7f 100644\n--- a/tests/components/youless/snapshots/test_sensor.ambr\n+++ b/tests/components/youless/snapshots/test_sensor.ambr\n@@ -152,6 +152,57 @@\n     'state': '1624.264',\n   })\n # ---\n+# name: test_sensors[sensor.power_meter_average_peak-entry]\n+  EntityRegistryEntrySnapshot({\n+    'aliases': set({\n+    }),\n+    'area_id': None,\n+    'capabilities': dict({\n+      'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>,\n+    }),\n+    'config_entry_id': <ANY>,\n+    'device_class': None,\n+    'device_id': <ANY>,\n+    'disabled_by': None,\n+    'domain': 'sensor',\n+    'entity_category': None,\n+    'entity_id': 'sensor.power_meter_average_peak',\n+    'has_entity_name': True,\n+    'hidden_by': None,\n+    'icon': None,\n+    'id': <ANY>,\n+    'labels': set({\n+    }),\n+    'name': None,\n+    'options': dict({\n+    }),\n+    'original_device_class': <SensorDeviceClass.POWER: 'power'>,\n+    'original_icon': None,\n+    'original_name': 'Average peak',\n+    'platform': 'youless',\n+    'previous_unique_id': None,\n+    'supported_features': 0,\n+    'translation_key': 'average_peak',\n+    'unique_id': 'youless_localhost_average_peak',\n+    'unit_of_measurement': <UnitOfPower.WATT: 'W'>,\n+  })\n+# ---\n+# name: test_sensors[sensor.power_meter_average_peak-state]\n+  StateSnapshot({\n+    'attributes': ReadOnlyDict({\n+      'device_class': 'power',\n+      'friendly_name': 'Power meter Average peak',\n+      'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>,\n+      'unit_of_measurement': <UnitOfPower.WATT: 'W'>,\n+    }),\n+    'context': <ANY>,\n+    'entity_id': 'sensor.power_meter_average_peak',\n+    'last_changed': <ANY>,\n+    'last_reported': <ANY>,\n+    'last_updated': <ANY>,\n+    'state': '400',\n+  })\n+# ---\n # name: test_sensors[sensor.power_meter_current_phase_1-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n@@ -200,7 +251,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '0.123',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_current_phase_2-entry]\n@@ -251,7 +302,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '0.123',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_current_phase_3-entry]\n@@ -302,7 +353,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '0.123',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_current_power_usage-entry]\n@@ -458,6 +509,57 @@\n     'state': '4490.631',\n   })\n # ---\n+# name: test_sensors[sensor.power_meter_month_peak-entry]\n+  EntityRegistryEntrySnapshot({\n+    'aliases': set({\n+    }),\n+    'area_id': None,\n+    'capabilities': dict({\n+      'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>,\n+    }),\n+    'config_entry_id': <ANY>,\n+    'device_class': None,\n+    'device_id': <ANY>,\n+    'disabled_by': None,\n+    'domain': 'sensor',\n+    'entity_category': None,\n+    'entity_id': 'sensor.power_meter_month_peak',\n+    'has_entity_name': True,\n+    'hidden_by': None,\n+    'icon': None,\n+    'id': <ANY>,\n+    'labels': set({\n+    }),\n+    'name': None,\n+    'options': dict({\n+    }),\n+    'original_device_class': <SensorDeviceClass.POWER: 'power'>,\n+    'original_icon': None,\n+    'original_name': 'Month peak',\n+    'platform': 'youless',\n+    'previous_unique_id': None,\n+    'supported_features': 0,\n+    'translation_key': 'month_peak',\n+    'unique_id': 'youless_localhost_month_peak',\n+    'unit_of_measurement': <UnitOfPower.WATT: 'W'>,\n+  })\n+# ---\n+# name: test_sensors[sensor.power_meter_month_peak-state]\n+  StateSnapshot({\n+    'attributes': ReadOnlyDict({\n+      'device_class': 'power',\n+      'friendly_name': 'Power meter Month peak',\n+      'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>,\n+      'unit_of_measurement': <UnitOfPower.WATT: 'W'>,\n+    }),\n+    'context': <ANY>,\n+    'entity_id': 'sensor.power_meter_month_peak',\n+    'last_changed': <ANY>,\n+    'last_reported': <ANY>,\n+    'last_updated': <ANY>,\n+    'state': '1200',\n+  })\n+# ---\n # name: test_sensors[sensor.power_meter_power_phase_1-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n@@ -506,7 +608,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '462',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_power_phase_2-entry]\n@@ -557,7 +659,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '230',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_power_phase_3-entry]\n@@ -608,7 +710,63 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '230',\n+  })\n+# ---\n+# name: test_sensors[sensor.power_meter_tariff-entry]\n+  EntityRegistryEntrySnapshot({\n+    'aliases': set({\n+    }),\n+    'area_id': None,\n+    'capabilities': dict({\n+      'options': list([\n+        '1',\n+        '2',\n+      ]),\n+    }),\n+    'config_entry_id': <ANY>,\n+    'device_class': None,\n+    'device_id': <ANY>,\n+    'disabled_by': None,\n+    'domain': 'sensor',\n+    'entity_category': None,\n+    'entity_id': 'sensor.power_meter_tariff',\n+    'has_entity_name': True,\n+    'hidden_by': None,\n+    'icon': None,\n+    'id': <ANY>,\n+    'labels': set({\n+    }),\n+    'name': None,\n+    'options': dict({\n+    }),\n+    'original_device_class': <SensorDeviceClass.ENUM: 'enum'>,\n+    'original_icon': None,\n+    'original_name': 'Tariff',\n+    'platform': 'youless',\n+    'previous_unique_id': None,\n+    'supported_features': 0,\n+    'translation_key': 'active_tariff',\n+    'unique_id': 'youless_localhost_tariff',\n+    'unit_of_measurement': None,\n+  })\n+# ---\n+# name: test_sensors[sensor.power_meter_tariff-state]\n+  StateSnapshot({\n+    'attributes': ReadOnlyDict({\n+      'device_class': 'enum',\n+      'friendly_name': 'Power meter Tariff',\n+      'options': list([\n+        '1',\n+        '2',\n+      ]),\n+    }),\n+    'context': <ANY>,\n+    'entity_id': 'sensor.power_meter_tariff',\n+    'last_changed': <ANY>,\n+    'last_reported': <ANY>,\n+    'last_updated': <ANY>,\n+    'state': '1',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_total_energy_import-entry]\n@@ -710,7 +868,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '240',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_voltage_phase_2-entry]\n@@ -761,7 +919,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '240',\n   })\n # ---\n # name: test_sensors[sensor.power_meter_voltage_phase_3-entry]\n@@ -812,7 +970,7 @@\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'unknown',\n+    'state': '240',\n   })\n # ---\n # name: test_sensors[sensor.s0_meter_current_usage-entry]\ndiff --git a/tests/components/youless/test_init.py b/tests/components/youless/test_init.py\nindex 29db8c66af0b57..9f0956cea359a6 100644\n--- a/tests/components/youless/test_init.py\n+++ b/tests/components/youless/test_init.py\n@@ -15,4 +15,4 @@ async def test_async_setup_entry(hass: HomeAssistant) -> None:\n \n     assert await setup.async_setup_component(hass, youless.DOMAIN, {})\n     assert entry.state is ConfigEntryState.LOADED\n-    assert len(hass.states.async_entity_ids()) == 19\n+    assert len(hass.states.async_entity_ids()) == 22\n", "problem_statement": "Youless integration - missing Belgian info Tarif & Month peak\n### The problem\n\nHi, \nIn order to do load balancing with my consumed electricity and EV charging, I installed as a first step the Youless dongle and integrated in HA. All works well, but I am missing the following 2 parameters which are essential in Belgium. These are the \"Tarif\" and the \"Month Peak\". \nI see the values in the Youless app, but can't get it into HA. \nCould anyone help to visualize please? \n\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.1.2\n\n### What was the last working version of Home Assistant Core?\n\ncore-2025.1.2\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nYouless\n\n### Link to integration documentation on our website\n\nhttps://www.home-assistant.io/integrations/youless\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n\n![Image](https://github.com/user-attachments/assets/06a69b13-2094-4a10-a263-9f73d65a3a7f)\n", "hints_text": "\nHey there @gjong, mind taking a look at this issue as it has been labeled with an integration (`youless`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1752) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `youless` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign youless` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[youless documentation](https://www.home-assistant.io/integrations/youless)\n[youless source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/youless)\n<sub><sup>(message by IssueLinks)</sup></sub>\nI will need to have a deeper look into the integration. The Tarif should be exposed in the library underneath. The Month peak I have no clue what that is, so that must have been added recently in the firmware. I will need to dig up the latest documentation and check for you.\n@MikeLeem could you share an example JSON from the YouLess device phase end point. You can access this by loading:\n\n    http://<youless_ip>/f\n\nThe documentation is a bit vague about how the response values would look.\n\nhttps://github.com/gjong\u2002\u2002\nHello,\nPlease find the printscreen of the measurement points.\nI believe the required sensors are (from what I can see):\n\n  *\n\"tr\" which is the Tarif. Status can be 1 or 2 in value.\n  *\n\"pp\" which is the Month peak. This value is expressed in unit Watt\n\n[cid:09958ac4-9520-404a-8288-080143ce93da]\n\nThanks!\n\nSorry.. Now with the correct picture: \n\n\n<img width=\"149\" alt=\"Image\" src=\"https://github.com/user-attachments/assets/2e248c0c-54b3-412c-b3c7-8179b018083a\" />\n\n________________________________\nFrom: Gerben Jongerius ***@***.***>\nSent: Thursday, January 16, 2025 12:23\nTo: home-assistant/core ***@***.***>\nCc: MikeLeem ***@***.***>; Mention ***@***.***>\nSubject: Re: [home-assistant/core] Youless integration - missing Belgian info Tarif & Month peak (Issue #135737)\n\n\n@MikeLeem<https://github.com/MikeLeem> could you share an example JSON from the YouLess device phase end point. You can access this by loading:\n\nhttp://<youless_ip>/f\n\n\nThe documentation is a bit vague about how the response values would look.\n\n\u2014\nReply to this email directly, view it on GitHub<https://github.com/home-assistant/core/issues/135737#issuecomment-2595261361>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BORLL5FMDG47JOTCS7J7DB32K6JCPAVCNFSM6AAAAABVIHNKDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOJVGI3DCMZWGE>.\nYou are receiving this because you were mentioned.\n", "created_at": "2025-01-30T12:20:14Z"}
{"repo": "home-assistant/core", "pull_number": 136911, "instance_id": "home-assistant__core-136911", "issue_numbers": ["136863"], "base_commit": "5dd147e83b3f02e7da75c33513760967b51850b9", "patch": "diff --git a/homeassistant/components/opower/coordinator.py b/homeassistant/components/opower/coordinator.py\nindex f6f3524d630875..6957ae4984c73a 100644\n--- a/homeassistant/components/opower/coordinator.py\n+++ b/homeassistant/components/opower/coordinator.py\n@@ -5,18 +5,16 @@\n from types import MappingProxyType\n from typing import Any, cast\n \n-import aiohttp\n from opower import (\n     Account,\n     AggregateType,\n-    CannotConnect,\n     CostRead,\n     Forecast,\n-    InvalidAuth,\n     MeterType,\n     Opower,\n     ReadResolution,\n )\n+from opower.exceptions import ApiException, CannotConnect, InvalidAuth\n \n from homeassistant.components.recorder import get_instance\n from homeassistant.components.recorder.models import StatisticData, StatisticMetaData\n@@ -89,7 +87,7 @@ async def _async_update_data(\n             raise UpdateFailed(f\"Error during login: {err}\") from err\n         try:\n             forecasts: list[Forecast] = await self.api.async_get_forecast()\n-        except aiohttp.ClientError as err:\n+        except ApiException as err:\n             _LOGGER.error(\"Error getting forecasts: %s\", err)\n             raise\n         _LOGGER.debug(\"Updating sensor data with: %s\", forecasts)\n@@ -102,7 +100,7 @@ async def _insert_statistics(self) -> None:\n         \"\"\"Insert Opower statistics.\"\"\"\n         try:\n             accounts = await self.api.async_get_accounts()\n-        except aiohttp.ClientError as err:\n+        except ApiException as err:\n             _LOGGER.error(\"Error getting accounts: %s\", err)\n             raise\n         for account in accounts:\n@@ -271,7 +269,7 @@ def _update_with_finer_cost_reads(\n             cost_reads = await self.api.async_get_cost_reads(\n                 account, AggregateType.BILL, start, end\n             )\n-        except aiohttp.ClientError as err:\n+        except ApiException as err:\n             _LOGGER.error(\"Error getting monthly cost reads: %s\", err)\n             raise\n         _LOGGER.debug(\"Got %s monthly cost reads\", len(cost_reads))\n@@ -290,7 +288,7 @@ def _update_with_finer_cost_reads(\n             daily_cost_reads = await self.api.async_get_cost_reads(\n                 account, AggregateType.DAY, start, end\n             )\n-        except aiohttp.ClientError as err:\n+        except ApiException as err:\n             _LOGGER.error(\"Error getting daily cost reads: %s\", err)\n             raise\n         _LOGGER.debug(\"Got %s daily cost reads\", len(daily_cost_reads))\n@@ -308,7 +306,7 @@ def _update_with_finer_cost_reads(\n             hourly_cost_reads = await self.api.async_get_cost_reads(\n                 account, AggregateType.HOUR, start, end\n             )\n-        except aiohttp.ClientError as err:\n+        except ApiException as err:\n             _LOGGER.error(\"Error getting hourly cost reads: %s\", err)\n             raise\n         _LOGGER.debug(\"Got %s hourly cost reads\", len(hourly_cost_reads))\ndiff --git a/homeassistant/components/opower/manifest.json b/homeassistant/components/opower/manifest.json\nindex 7227f7171ac0a6..d168cba5752847 100644\n--- a/homeassistant/components/opower/manifest.json\n+++ b/homeassistant/components/opower/manifest.json\n@@ -7,5 +7,5 @@\n   \"documentation\": \"https://www.home-assistant.io/integrations/opower\",\n   \"iot_class\": \"cloud_polling\",\n   \"loggers\": [\"opower\"],\n-  \"requirements\": [\"opower==0.8.8\"]\n+  \"requirements\": [\"opower==0.8.9\"]\n }\ndiff --git a/homeassistant/components/opower/sensor.py b/homeassistant/components/opower/sensor.py\nindex 7f8eb22d1e645c..f9d0fe6233270f 100644\n--- a/homeassistant/components/opower/sensor.py\n+++ b/homeassistant/components/opower/sensor.py\n@@ -97,7 +97,7 @@ class OpowerEntityDescription(SensorEntityDescription):\n         device_class=SensorDeviceClass.DATE,\n         entity_category=EntityCategory.DIAGNOSTIC,\n         entity_registry_enabled_default=False,\n-        value_fn=lambda data: data.start_date,\n+        value_fn=lambda data: str(data.start_date),\n     ),\n     OpowerEntityDescription(\n         key=\"elec_end_date\",\n@@ -105,7 +105,7 @@ class OpowerEntityDescription(SensorEntityDescription):\n         device_class=SensorDeviceClass.DATE,\n         entity_category=EntityCategory.DIAGNOSTIC,\n         entity_registry_enabled_default=False,\n-        value_fn=lambda data: data.end_date,\n+        value_fn=lambda data: str(data.end_date),\n     ),\n )\n GAS_SENSORS: tuple[OpowerEntityDescription, ...] = (\n@@ -169,7 +169,7 @@ class OpowerEntityDescription(SensorEntityDescription):\n         device_class=SensorDeviceClass.DATE,\n         entity_category=EntityCategory.DIAGNOSTIC,\n         entity_registry_enabled_default=False,\n-        value_fn=lambda data: data.start_date,\n+        value_fn=lambda data: str(data.start_date),\n     ),\n     OpowerEntityDescription(\n         key=\"gas_end_date\",\n@@ -177,7 +177,7 @@ class OpowerEntityDescription(SensorEntityDescription):\n         device_class=SensorDeviceClass.DATE,\n         entity_category=EntityCategory.DIAGNOSTIC,\n         entity_registry_enabled_default=False,\n-        value_fn=lambda data: data.end_date,\n+        value_fn=lambda data: str(data.end_date),\n     ),\n )\n \ndiff --git a/requirements_all.txt b/requirements_all.txt\nindex 16079cca64dab0..2025cbbd0ac9c4 100644\n--- a/requirements_all.txt\n+++ b/requirements_all.txt\n@@ -1592,7 +1592,7 @@ openwrt-luci-rpc==1.1.17\n openwrt-ubus-rpc==0.0.2\n \n # homeassistant.components.opower\n-opower==0.8.8\n+opower==0.8.9\n \n # homeassistant.components.oralb\n oralb-ble==0.17.6\n", "test_patch": "diff --git a/requirements_test_all.txt b/requirements_test_all.txt\nindex a5bd58dff58c64..9575401c62cea3 100644\n--- a/requirements_test_all.txt\n+++ b/requirements_test_all.txt\n@@ -1328,7 +1328,7 @@ openhomedevice==2.2.0\n openwebifpy==4.3.1\n \n # homeassistant.components.opower\n-opower==0.8.8\n+opower==0.8.9\n \n # homeassistant.components.oralb\n oralb-ble==0.17.6\n", "problem_statement": "No AMI UtilityAccounts found\n### The problem\n\nhello!\n\nUpon updating to 2025.2.0b0, i noticed this log that appears. It also appears when i reload the integation.\n\nThe provider is Enmax.\n\nthanks\n\n```\nLogger: /usr/local/lib/python3.13/site-packages/opower/opower.py\nSource: components/opower/coordinator.py:91\nFirst occurred: 11:04:58 AM (1 occurrences)\nLast logged: 11:04:58 AM\n\nError server response: {\"error\":{\"details\":\"No AMI UtilityAccounts found for specified customer.\",\"serviceErrorCode\":\"NO_AMI_ACCOUNTS\"}}\n```\n\n### What version of Home Assistant Core has the issue?\n\n2025.2.0b0\n\n### What was the last working version of Home Assistant Core?\n\n2025.1.x\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nOpower Enmax\n\n### Link to integration documentation on our website\n\nhttps://www.home-assistant.io/integrations/opower/\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @tronikos, mind taking a look at this issue as it has been labeled with an integration (`opower`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1106) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `opower` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign opower` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[opower documentation](https://www.home-assistant.io/integrations/opower)\n[opower source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/opower)\n<sub><sup>(message by IssueLinks)</sup></sub>\nCan you enable debug logs and attach them here or privately share them with me on discord?", "created_at": "2025-01-30T10:48:06Z"}
{"repo": "home-assistant/core", "pull_number": 136910, "instance_id": "home-assistant__core-136910", "issue_numbers": ["136897"], "base_commit": "9eb383f3148c559995631bc4ae44269f67d9f3cd", "patch": "diff --git a/homeassistant/components/onedrive/backup.py b/homeassistant/components/onedrive/backup.py\nindex a5a5c01979779f..94d60bc6398125 100644\n--- a/homeassistant/components/onedrive/backup.py\n+++ b/homeassistant/components/onedrive/backup.py\n@@ -190,7 +190,13 @@ async def async_delete_backup(\n         **kwargs: Any,\n     ) -> None:\n         \"\"\"Delete a backup file.\"\"\"\n-        await self._get_backup_file_item(backup_id).delete()\n+\n+        try:\n+            await self._get_backup_file_item(backup_id).delete()\n+        except APIError as err:\n+            if err.response_status_code == 404:\n+                return\n+            raise\n \n     @handle_backup_errors\n     async def async_list_backups(self, **kwargs: Any) -> list[AgentBackup]:\n", "test_patch": "diff --git a/tests/components/onedrive/test_backup.py b/tests/components/onedrive/test_backup.py\nindex a3d1129377fc88..3492202d3feb08 100644\n--- a/tests/components/onedrive/test_backup.py\n+++ b/tests/components/onedrive/test_backup.py\n@@ -156,6 +156,28 @@ async def test_agents_delete(\n     mock_drive_items.delete.assert_called_once()\n \n \n+async def test_agents_delete_not_found_does_not_throw(\n+    hass: HomeAssistant,\n+    hass_ws_client: WebSocketGenerator,\n+    mock_drive_items: MagicMock,\n+) -> None:\n+    \"\"\"Test agent delete backup.\"\"\"\n+    mock_drive_items.delete = AsyncMock(side_effect=APIError(response_status_code=404))\n+    client = await hass_ws_client(hass)\n+\n+    await client.send_json_auto_id(\n+        {\n+            \"type\": \"backup/delete\",\n+            \"backup_id\": BACKUP_METADATA[\"backup_id\"],\n+        }\n+    )\n+    response = await client.receive_json()\n+\n+    assert response[\"success\"]\n+    assert response[\"result\"] == {\"agent_errors\": {}}\n+    mock_drive_items.delete.assert_called_once()\n+\n+\n async def test_agents_upload(\n     hass_client: ClientSessionGenerator,\n     caplog: pytest.LogCaptureFixture,\n@@ -257,7 +279,7 @@ async def test_agents_download(\n     (\"side_effect\", \"error\"),\n     [\n         (\n-            APIError(response_status_code=404, message=\"File not found.\"),\n+            APIError(response_status_code=500),\n             \"Backup operation failed\",\n         ),\n         (TimeoutError(), \"Backup operation timed out\"),\n", "problem_statement": "Backup Error 2025.2.0b1\n### The problem\n\nBackup throws this error when backing up.  Two backups have been made and the retain setting is 6 \n```\n2025-01-30 02:19:57.150 ERROR (MainThread) [homeassistant.components.onedrive.backup] Error during backup in async_delete_backup: Status 404, message None\n2025-01-30 02:19:57.242 ERROR (MainThread) [homeassistant.components.backup] Error deleting old copies: {'a694ecad': {'onedrive.D378A3F5743D8717': BackupAgentError('Backup operation failed')}}\n```\nI'm backing up to local, local network share, Google Drive, and One Drive\n\n\n### What version of Home Assistant Core has the issue?\n\n2025.2.0b1\n\n### What was the last working version of Home Assistant Core?\n\n2025.1.1\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nBackup\n\n### Link to integration documentation on our website\n\n_No response_\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @home-assistant/core, mind taking a look at this issue as it has been labeled with an integration (`backup`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L183) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `backup` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign backup` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[backup documentation](https://www.home-assistant.io/integrations/backup)\n[backup source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/backup)\n<sub><sup>(message by IssueLinks)</sup></sub>\n\nHey there @zweckj, mind taking a look at this issue as it has been labeled with an integration (`onedrive`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1076) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `onedrive` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign onedrive` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[onedrive documentation](https://www.home-assistant.io/integrations/onedrive)\n[onedrive source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/onedrive)\n<sub><sup>(message by IssueLinks)</sup></sub>\nIt looks like it couldn't find the backup `a694ecad` in the OneDrive.\nDo you by any chance know if that's a backup that should have been uploaded to OneDrive? Can you also check your OneDrive if there is a file in the backup folder called `a694ecad.tar`?\n![Image](https://github.com/user-attachments/assets/9dbe8bc9-4c1d-4853-a2b5-a7c92dda2a93)\n\nDoesn't seem like it\n\n(Image from the beta channel)", "created_at": "2025-01-30T10:36:31Z"}
{"repo": "home-assistant/core", "pull_number": 136888, "instance_id": "home-assistant__core-136888", "issue_numbers": ["136869"], "base_commit": "64b056fbe998cf7231906c26f4daab02bb4124a5", "patch": "diff --git a/homeassistant/components/nest/manifest.json b/homeassistant/components/nest/manifest.json\nindex f7e78b2d538e15..cd961276082909 100644\n--- a/homeassistant/components/nest/manifest.json\n+++ b/homeassistant/components/nest/manifest.json\n@@ -19,5 +19,5 @@\n   \"documentation\": \"https://www.home-assistant.io/integrations/nest\",\n   \"iot_class\": \"cloud_push\",\n   \"loggers\": [\"google_nest_sdm\"],\n-  \"requirements\": [\"google-nest-sdm==7.1.0\"]\n+  \"requirements\": [\"google-nest-sdm==7.1.1\"]\n }\ndiff --git a/requirements_all.txt b/requirements_all.txt\nindex 16079cca64dab0..90a8709395fae1 100644\n--- a/requirements_all.txt\n+++ b/requirements_all.txt\n@@ -1036,7 +1036,7 @@ google-cloud-texttospeech==2.17.2\n google-generativeai==0.8.2\n \n # homeassistant.components.nest\n-google-nest-sdm==7.1.0\n+google-nest-sdm==7.1.1\n \n # homeassistant.components.google_photos\n google-photos-library-api==0.12.1\n", "test_patch": "diff --git a/requirements_test_all.txt b/requirements_test_all.txt\nindex a5bd58dff58c64..c7a0959bbb81fd 100644\n--- a/requirements_test_all.txt\n+++ b/requirements_test_all.txt\n@@ -886,7 +886,7 @@ google-cloud-texttospeech==2.17.2\n google-generativeai==0.8.2\n \n # homeassistant.components.nest\n-google-nest-sdm==7.1.0\n+google-nest-sdm==7.1.1\n \n # homeassistant.components.google_photos\n google-photos-library-api==0.12.1\n", "problem_statement": "Significant CPU usage from Nest\n### The problem\n\nhello!\n\nUpon updating to 2025.2.0b0, i noticed my CPU usage has significantly increased on my Nuc12 running HAOS 14.2\n\n![Image](https://github.com/user-attachments/assets/d96c23a7-6647-4409-91f9-e68d86aa9ba4)\n\nCallgrinds indicate its coming from the Nest integration.\n\n![Image](https://github.com/user-attachments/assets/01d54102-6992-4703-9ab7-ddbc303b2373)\n\n```\nfl=/usr/local/lib/python3.13/site-packages/grpc/aio/_call.py\nfn=_consume_request_iterator\n443 1477298196\ncfl=/usr/local/lib/python3.13/site-packages/google_nest_sdm/subscriber_client.py\ncfn=pull_request_generator\ncalls=1347207 100\n443 17602072572\ncfl=/usr/local/lib/python3.13/site-packages/grpc/aio/_call.py\ncfn=_write\ncalls=2694414 487\n443 14591881753\n```\n\nCurrently, I have 4 devices on the Nest integration, 3 Hub Max's and 1 Second Gen Thermostat.\n\nCallgrinds attached (please remove .txt from file extension)\n\nmaybe related to this issue https://github.com/home-assistant/core/issues/108065\n\n### What version of Home Assistant Core has the issue?\n\n2025.2.0b0\n\n### What was the last working version of Home Assistant Core?\n\n2025.1.x\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nNest\n\n### Link to integration documentation on our website\n\nhttps://www.home-assistant.io/integrations/nest/\n\n### Diagnostics information\n\n[removed]\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @allenporter, mind taking a look at this issue as it has been labeled with an integration (`nest`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L996) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `nest` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign nest` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[nest documentation](https://www.home-assistant.io/integrations/nest)\n[nest source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/nest)\n<sub><sup>(message by IssueLinks)</sup></sub>\nconfirming that if i disable the nest integration, my CPU levels drop back down to normal ~2%\njumping in here.  updated to beta 2 and my cpu went through the roof.  also have the google nest integration.  2 thermostats and a nest doorbell.  went back to 2025.1.4\nThanks! we have enough data for now to investigate.\nFor visibility, i rewrote the nest pub/sub subscription in this release. The previous version used threads and i think was getting stuck. The new version is fully asyncio, though clearly has another issue. https://github.com/allenporter/python-google-nest-sdm/pull/1146 is the change upstream.\nI am able to reproduce the issue, i see home assistant using 100% of one of my cpus.", "created_at": "2025-01-30T05:50:04Z"}
{"repo": "home-assistant/core", "pull_number": 136793, "instance_id": "home-assistant__core-136793", "issue_numbers": ["136340"], "base_commit": "64cda8cdb8a08fa3ab1f767cc8dcdc48d7201152", "patch": "diff --git a/homeassistant/components/totalconnect/alarm_control_panel.py b/homeassistant/components/totalconnect/alarm_control_panel.py\nindex 48ba78acc9298c..021d1c7b88668f 100644\n--- a/homeassistant/components/totalconnect/alarm_control_panel.py\n+++ b/homeassistant/components/totalconnect/alarm_control_panel.py\n@@ -73,7 +73,7 @@ def __init__(\n     ) -> None:\n         \"\"\"Initialize the TotalConnect status.\"\"\"\n         super().__init__(coordinator, location)\n-        self._partition_id = partition_id\n+        self._partition_id = int(partition_id)\n         self._partition = self._location.partitions[partition_id]\n \n         \"\"\"\n@@ -81,7 +81,7 @@ def __init__(\n         for most users with new support for partitions.\n         Add _# for partition 2 and beyond.\n         \"\"\"\n-        if partition_id == 1:\n+        if int(partition_id) == 1:\n             self._attr_name = None\n             self._attr_unique_id = str(location.location_id)\n         else:\ndiff --git a/homeassistant/components/totalconnect/manifest.json b/homeassistant/components/totalconnect/manifest.json\nindex 33306a7adbac24..6aff1ea392b3f0 100644\n--- a/homeassistant/components/totalconnect/manifest.json\n+++ b/homeassistant/components/totalconnect/manifest.json\n@@ -6,5 +6,5 @@\n   \"documentation\": \"https://www.home-assistant.io/integrations/totalconnect\",\n   \"iot_class\": \"cloud_polling\",\n   \"loggers\": [\"total_connect_client\"],\n-  \"requirements\": [\"total-connect-client==2024.12\"]\n+  \"requirements\": [\"total-connect-client==2025.1.4\"]\n }\ndiff --git a/requirements_all.txt b/requirements_all.txt\nindex 24a550e05de28b..34842f77c182e9 100644\n--- a/requirements_all.txt\n+++ b/requirements_all.txt\n@@ -2895,7 +2895,7 @@ tololib==1.1.0\n toonapi==0.3.0\n \n # homeassistant.components.totalconnect\n-total-connect-client==2024.12\n+total-connect-client==2025.1.4\n \n # homeassistant.components.tplink_lte\n tp-connected==0.0.4\n", "test_patch": "diff --git a/requirements_test_all.txt b/requirements_test_all.txt\nindex fa1dd4bed7fd0a..23eb005cf021fe 100644\n--- a/requirements_test_all.txt\n+++ b/requirements_test_all.txt\n@@ -2323,7 +2323,7 @@ tololib==1.1.0\n toonapi==0.3.0\n \n # homeassistant.components.totalconnect\n-total-connect-client==2024.12\n+total-connect-client==2025.1.4\n \n # homeassistant.components.tplink_omada\n tplink-omada-client==1.4.3\ndiff --git a/tests/components/totalconnect/common.py b/tests/components/totalconnect/common.py\nindex 828cad71e077c0..34d451ec0b8bcc 100644\n--- a/tests/components/totalconnect/common.py\n+++ b/tests/components/totalconnect/common.py\n@@ -49,20 +49,15 @@\n     \"UserFeatureList\": \"Master=0,User Administration=0,Configuration Administration=0\",\n }\n \n-RESPONSE_AUTHENTICATE = {\n+RESPONSE_SESSION_DETAILS = {\n     \"ResultCode\": ResultCode.SUCCESS.value,\n-    \"SessionID\": 1,\n+    \"ResultData\": \"Success\",\n+    \"SessionID\": \"12345\",\n     \"Locations\": LOCATIONS,\n     \"ModuleFlags\": MODULE_FLAGS,\n     \"UserInfo\": USER,\n }\n \n-RESPONSE_AUTHENTICATE_FAILED = {\n-    \"ResultCode\": ResultCode.BAD_USER_OR_PASSWORD.value,\n-    \"ResultData\": \"test bad authentication\",\n-}\n-\n-\n PARTITION_DISARMED = {\n     \"PartitionID\": \"1\",\n     \"ArmingState\": ArmingState.DISARMED,\n@@ -359,13 +354,13 @@\n OPTIONS_DATA_CODE_REQUIRED = {AUTO_BYPASS: False, CODE_REQUIRED: True}\n \n PARTITION_DETAILS_1 = {\n-    \"PartitionID\": 1,\n+    \"PartitionID\": \"1\",\n     \"ArmingState\": ArmingState.DISARMED.value,\n     \"PartitionName\": \"Test1\",\n }\n \n PARTITION_DETAILS_2 = {\n-    \"PartitionID\": 2,\n+    \"PartitionID\": \"2\",\n     \"ArmingState\": ArmingState.DISARMED.value,\n     \"PartitionName\": \"Test2\",\n }\n@@ -402,6 +397,12 @@\n TOTALCONNECT_REQUEST = (\n     \"homeassistant.components.totalconnect.TotalConnectClient.request\"\n )\n+TOTALCONNECT_GET_CONFIG = (\n+    \"homeassistant.components.totalconnect.TotalConnectClient._get_configuration\"\n+)\n+TOTALCONNECT_REQUEST_TOKEN = (\n+    \"homeassistant.components.totalconnect.TotalConnectClient._request_token\"\n+)\n \n \n async def setup_platform(\n@@ -420,7 +421,7 @@ async def setup_platform(\n     mock_entry.add_to_hass(hass)\n \n     responses = [\n-        RESPONSE_AUTHENTICATE,\n+        RESPONSE_SESSION_DETAILS,\n         RESPONSE_PARTITION_DETAILS,\n         RESPONSE_GET_ZONE_DETAILS_SUCCESS,\n         RESPONSE_DISARMED,\n@@ -433,6 +434,8 @@ async def setup_platform(\n             TOTALCONNECT_REQUEST,\n             side_effect=responses,\n         ) as mock_request,\n+        patch(TOTALCONNECT_GET_CONFIG, side_effect=None),\n+        patch(TOTALCONNECT_REQUEST_TOKEN, side_effect=None),\n     ):\n         assert await async_setup_component(hass, DOMAIN, {})\n         assert mock_request.call_count == 5\n@@ -448,17 +451,21 @@ async def init_integration(hass: HomeAssistant) -> MockConfigEntry:\n     mock_entry.add_to_hass(hass)\n \n     responses = [\n-        RESPONSE_AUTHENTICATE,\n+        RESPONSE_SESSION_DETAILS,\n         RESPONSE_PARTITION_DETAILS,\n         RESPONSE_GET_ZONE_DETAILS_SUCCESS,\n         RESPONSE_DISARMED,\n         RESPONSE_DISARMED,\n     ]\n \n-    with patch(\n-        TOTALCONNECT_REQUEST,\n-        side_effect=responses,\n-    ) as mock_request:\n+    with (\n+        patch(\n+            TOTALCONNECT_REQUEST,\n+            side_effect=responses,\n+        ) as mock_request,\n+        patch(TOTALCONNECT_GET_CONFIG, side_effect=None),\n+        patch(TOTALCONNECT_REQUEST_TOKEN, side_effect=None),\n+    ):\n         await hass.config_entries.async_setup(mock_entry.entry_id)\n         assert mock_request.call_count == 5\n     await hass.async_block_till_done()\ndiff --git a/tests/components/totalconnect/test_config_flow.py b/tests/components/totalconnect/test_config_flow.py\nindex 86419bff817f4f..f5020394bce065 100644\n--- a/tests/components/totalconnect/test_config_flow.py\n+++ b/tests/components/totalconnect/test_config_flow.py\n@@ -18,13 +18,15 @@\n from .common import (\n     CONFIG_DATA,\n     CONFIG_DATA_NO_USERCODES,\n-    RESPONSE_AUTHENTICATE,\n     RESPONSE_DISARMED,\n     RESPONSE_GET_ZONE_DETAILS_SUCCESS,\n     RESPONSE_PARTITION_DETAILS,\n+    RESPONSE_SESSION_DETAILS,\n     RESPONSE_SUCCESS,\n     RESPONSE_USER_CODE_INVALID,\n+    TOTALCONNECT_GET_CONFIG,\n     TOTALCONNECT_REQUEST,\n+    TOTALCONNECT_REQUEST_TOKEN,\n     USERNAME,\n )\n \n@@ -48,7 +50,7 @@ async def test_user_show_locations(hass: HomeAssistant) -> None:\n     \"\"\"Test user locations form.\"\"\"\n     # user/pass provided, so check if valid then ask for usercodes on locations form\n     responses = [\n-        RESPONSE_AUTHENTICATE,\n+        RESPONSE_SESSION_DETAILS,\n         RESPONSE_PARTITION_DETAILS,\n         RESPONSE_GET_ZONE_DETAILS_SUCCESS,\n         RESPONSE_DISARMED,\n@@ -61,6 +63,8 @@ async def test_user_show_locations(hass: HomeAssistant) -> None:\n             TOTALCONNECT_REQUEST,\n             side_effect=responses,\n         ) as mock_request,\n+        patch(TOTALCONNECT_GET_CONFIG, side_effect=None),\n+        patch(TOTALCONNECT_REQUEST_TOKEN, side_effect=None),\n         patch(\n             \"homeassistant.components.totalconnect.async_setup_entry\", return_value=True\n         ),\n@@ -180,7 +184,7 @@ async def test_reauth(hass: HomeAssistant) -> None:\n async def test_no_locations(hass: HomeAssistant) -> None:\n     \"\"\"Test with no user locations.\"\"\"\n     responses = [\n-        RESPONSE_AUTHENTICATE,\n+        RESPONSE_SESSION_DETAILS,\n         RESPONSE_PARTITION_DETAILS,\n         RESPONSE_GET_ZONE_DETAILS_SUCCESS,\n         RESPONSE_DISARMED,\n@@ -191,6 +195,8 @@ async def test_no_locations(hass: HomeAssistant) -> None:\n             TOTALCONNECT_REQUEST,\n             side_effect=responses,\n         ) as mock_request,\n+        patch(TOTALCONNECT_GET_CONFIG, side_effect=None),\n+        patch(TOTALCONNECT_REQUEST_TOKEN, side_effect=None),\n         patch(\n             \"homeassistant.components.totalconnect.async_setup_entry\", return_value=True\n         ),\n@@ -221,7 +227,7 @@ async def test_options_flow(hass: HomeAssistant) -> None:\n     config_entry.add_to_hass(hass)\n \n     responses = [\n-        RESPONSE_AUTHENTICATE,\n+        RESPONSE_SESSION_DETAILS,\n         RESPONSE_PARTITION_DETAILS,\n         RESPONSE_GET_ZONE_DETAILS_SUCCESS,\n         RESPONSE_DISARMED,\n@@ -229,7 +235,11 @@ async def test_options_flow(hass: HomeAssistant) -> None:\n         RESPONSE_DISARMED,\n     ]\n \n-    with patch(TOTALCONNECT_REQUEST, side_effect=responses):\n+    with (\n+        patch(TOTALCONNECT_REQUEST, side_effect=responses),\n+        patch(TOTALCONNECT_GET_CONFIG, side_effect=None),\n+        patch(TOTALCONNECT_REQUEST_TOKEN, side_effect=None),\n+    ):\n         assert await hass.config_entries.async_setup(config_entry.entry_id)\n         await hass.async_block_till_done()\n \n", "problem_statement": "Error setting up entry Total Connect\n### The problem\n\nThe Total Connect integration is no longer working as of today. No system updates were made since it worked last. It stopped working overnight. I tried re-start and re-boot to no avail. Service (TotalConnect - Resideo - https://status.resideo.com/ ) itself appears to be up but integration fails. I am able to use their mobile app to arm/disarm system fine but not via HA.\n\nLogger: homeassistant.config_entries\nSource: config_entries.py:640\nFirst occurred: 6:17:11 AM (2 occurrences)\nLast logged: 7:46:46 AM\n\nError setting up entry Total Connect for totalconnect\nTraceback (most recent call last):\n  File \"/usr/src/homeassistant/homeassistant/config_entries.py\", line 640, in __async_setup_with_context\n    result = await component.async_setup_entry(hass, self)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/src/homeassistant/homeassistant/components/totalconnect/__init__.py\", line 36, in async_setup_entry\n    client = await hass.async_add_executor_job(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        TotalConnectClient, username, password, usercodes, bypass\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 96, in __init__\n    self.authenticate()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 296, in authenticate\n    response = self.request(\n        operation_name,\n        (self.username, self.password, self.API_APP_ID, self.API_APP_VERSION),\n    )\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 235, in request\n    self._raise_for_retry(response)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 157, in _raise_for_retry\n    rc = _ResultCode.from_response(response)\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/const.py\", line 154, in from_response\n    raise ServiceUnavailable(f\"Server returned empty response, check server status at {STATUS_URL}\") from None\ntotal_connect_client.exceptions.ServiceUnavailable: Server returned empty response, check server status at https://status.resideo.com/\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.1.3\n\n### What was the last working version of Home Assistant Core?\n\ncore-2025.1.3\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nTotalConnect\n\n### Link to integration documentation on our website\n\nhttps://www.home-assistant.io/integrations/totalconnect/\n\n### Diagnostics information\n\nLogger: homeassistant.config_entries\nSource: config_entries.py:640\nFirst occurred: 6:17:11 AM (2 occurrences)\nLast logged: 7:46:46 AM\n\nError setting up entry Total Connect for totalconnect\nTraceback (most recent call last):\n  File \"/usr/src/homeassistant/homeassistant/config_entries.py\", line 640, in __async_setup_with_context\n    result = await component.async_setup_entry(hass, self)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/src/homeassistant/homeassistant/components/totalconnect/__init__.py\", line 36, in async_setup_entry\n    client = await hass.async_add_executor_job(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        TotalConnectClient, username, password, usercodes, bypass\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 96, in __init__\n    self.authenticate()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 296, in authenticate\n    response = self.request(\n        operation_name,\n        (self.username, self.password, self.API_APP_ID, self.API_APP_VERSION),\n    )\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 235, in request\n    self._raise_for_retry(response)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 157, in _raise_for_retry\n    rc = _ResultCode.from_response(response)\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/const.py\", line 154, in from_response\n    raise ServiceUnavailable(f\"Server returned empty response, check server status at {STATUS_URL}\") from None\ntotal_connect_client.exceptions.ServiceUnavailable: Server returned empty response, check server status at https://status.resideo.com/\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @austinmroczek, mind taking a look at this issue as it has been labeled with an integration (`totalconnect`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1554) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `totalconnect` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign totalconnect` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[totalconnect documentation](https://www.home-assistant.io/integrations/totalconnect)\n[totalconnect source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/totalconnect)\n<sub><sup>(message by IssueLinks)</sup></sub>\nSame issue, same error logs here.\nSame issue on my end\nSame, started about 8 hours ago while on HA 1.2. Updated to 1.3 and same thing.\n\n`Core\n2025.1.3\nSupervisor\n2024.12.3\nOperating System\n14.1\nFrontend\n20250109.0`\nSame issue, stopped overnight, however I can confirm it was working for 2 days on HA 2025.1.3 with no issues. \nThe error may indicate some sort of API change or issue at Resideo.\n\n`total_connect_client.exceptions.ServiceUnavailable: Server returned empty response`\n\nTheir status page doesn't seem to be reporting any related issues as of yet.\nhttps://status.resideo.com/\nHI,\n\nI got the same issue.\nSame\nSame\n\nI have the exact same issue.\nSame issue here as well\nSame\nUP ! Same here\nYep, same.  The day after I get this integration running for the first time.  \nSame the Resideo app on my phone does say it was recently updated and is requiring me to re sign in again.  So maybe something changed?\nWill investigate as soon as possible.  This seems like similar website/API problems in the past\nService went down for me today. And up to 7:31 AM CST it was working correctly.  Now I get: this every time I try to reload the integration\n\n```\n File \"/usr/local/lib/python3.13/site-packages/total_connect_client/const.py\", line 154, in from_response\n    raise ServiceUnavailable(f\"Server returned empty response, check server status at {STATUS_URL}\") from None\ntotal_connect_client.exceptions.ServiceUnavailable: Server returned empty response, check server status at https://status.resideo.com/\n```\n\nIt smells like API outage because the status at resideo is all green. And the TC app is still working (somewhat).\nsame here\nSame....\nSame for me. \nI agree it looks like an API outage, but Amazon Alexa is still working, and I would think that also uses the API service.\n> I agree it looks like an API outage, but Amazon Alexa is still working, and I would think that also uses the API service.\n\nIFTTT is still working with no interruptions as well.  \nIf Alexa and IFTTT work it has to be something with HA,  Thoughts?\nConsidering it worked initially on v2025.1.3, and it went down for all of us at about the same time, and considering it works fine with Alexa, could it be that Resideo is blocking API calls from unknown (non-AWS/Alexa) IP addresses?   If they use the same API?  Hopefully they didn\u2019t do what MyQ did and cut us off.  BTW, I just upgraded to v2025.1.4, and no change.  TotalConnect is still down.  I hope this is fixable.  I have a lot of automations that are based on the state of the security system.  \nIt's an issue with the SOAP API. When making a request to the AuthenticateUserLogin API, it responds with a 200 but the response is missing the SOAP body that should include the SessionID\n\nhttps://rs.alarmnet.com/tc21api/tc2.asmx?op=AuthenticateUserLogin\n\nThis is what the response should look like:\n\n```\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  <soap:Body>\n    <AuthenticateUserLoginResponse xmlns=\"https://services.alarmnet.com/TC2/\">\n      <AuthenticateUserLoginResult>\n        <SessionID>string</SessionID>\n      </AuthenticateUserLoginResult>\n    </AuthenticateUserLoginResponse>\n  </soap:Body>\n</soap:Envelope>\n```\n\nThis is the response I see instead:\n\n```\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap12:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap12=\"http://www.w3.org/2003/05/soap-envelope\">\n\t<soap:Body>\n\t\t<AuthenticateUserLoginResponse xmlns=\"https://services.alarmnet.com/TC2/\" />\n\t</soap:Body>\n</soap:Envelope>\n```\nWould a new alarm monitoring service fix it? anyone have any suggestions?\nI am the integration owner for the `totalconnect` integration in Home Assistant, and I maintain the underlying [total_connect_client](https://github.com/craigjmidwinter/total-connect-client) used to talk with the [TotalConnect 2.0 API](https://rs.alarmnet.com/TC21api/tc2.asmx).\n \nAs @thor0215 noted above, and I verified, the server is providing empty responses to all queries at the moment. This is a server problem, and has nothing to do with upgrading Home Assistant to 2025.1.x.\n\nWhen a user logs in, the API requires an `ApplicationID` be provided.  It is possible they have decided to block our ID. However, I would not jump to that conclusion yet.  I think it's more likely there is some weird server error that is not denying their main TotalConnect website/app, and they just haven't seen the problem yet. In the past we've seen the server status page show green, yet this integration was not working.\n\nResideo/Honeywell's business model is to sell alarms to third party installers (your alarm company).  They don't want to communicate with or support users directly.  All of their documentation essentially says 'contact your installer for help'. Folks could try to talk with Resideo/Honeywell.  One address I have found for them is `developerinfo@resideo.com` but in the past they have not responded to me.  They have a [contact page](https://www.hotfix.rde.resideo.com/us/en/corporate/contact-us/), and various social media handles [HoneywellHome Twitter/X](https://twitter.com/Honeywell_Home),  [Resideo Twitter/X](https://twitter.com/resideo), [HoneywellHome Facebook](https://www.facebook.com/honeywellhome), [Resideo Facebook](https://www.facebook.com/Resideo/) which is another way to try.  There is also a Homeowner support # [1-800-633-3991](tel:18006333991)\n\nI tried their online support chat earlier and got this:\n\n\"All of the security panels/systems along the TC2.0 app are not supported by this channel. These are only sold, installed and supported, by professional security providers/installers. For technical information, account management or general documentation, you can use our tool: https://www.resideo.com/us/en/find-a-pro/ To find a local security provider/installer that carries/services and supports this products.\"\n\nComplaining to your alarm company is another option. Changing alarm monitoring service will not fix this - though threatening to do so might motivate your current company to talk with Resideo.\n\nIt's a relatively minor thing, but it would also help to enable Analytics on your Home Assistant to help boost our numbers.  Right now we only show 265 active users on the [analytics page](https://analytics.home-assistant.io/integrations/).\nFollowing - literally just got around to automating our retail establishment's lights and heat based on alarm change. Can do a different way, but like having it linked. Thanks for working through this.\n> It's a relatively minor thing, but it would also help to enable Analytics on your Home Assistant to help boost our numbers. Right now we only show 265 active users on the [analytics page](https://analytics.home-assistant.io/integrations/).\n\nDone.  It looks like we need to have at least *Usage* analytics to report which integrations we are using.\n\nI instinctually disable/don't allow analytics when I set up systems.  But [reading up on HA's analytics](https://www.home-assistant.io/integrations/analytics/), I'm impressed by how open it is about the data it collects.  \nI routinely open up analytics.  I've had useful integrations disappear when there's too few users.\nThank you for the update @austinmroczek .  Wouldn't a server-side issue on the API also impact Alexa?  I appreciate all your efforts on this, but it has the same feel as when we were locked out of MyQ and Life360.  So disappointing that companies do this to their customers.  I spent so much time creating complex automations based on the state of the security system, as I'm sure many others did. I'll keep my fingers crossed that it gets resolved. \nI wish I had more concrete answers.  There is no insight into how the server works.  It's a logical assumption that if Alexa works, so should this.  However, in the past there were times when the TotalConnect app (iOS) worked but this did not, which is why I'm still holding out hope.  Past outages have been up to a couple of days, and since today is Friday, maybe it extends over the weekend.  If we still can't do anything by Monday my hope will quickly fade.\n\nI'm trying to work up some alternatives for folks.  Possibilities are:\n- IFTTT can communicate with TotalConnect and Home Assistant (via Webhooks). However this requires an IFTTT \"pro\" plan that is $2.92/month which is the same price I'm paying for TotalConnect right now.  Have not tried this yet due to the cost.\n- The newer Pro series panels support HomeKit.  I never bothered because I had the functionality I wanted.  I'll be testing this soon.  Assuming it works, this will probably leave most older, but still functional, alarm panels behind.\n\n[edited IFTTT pro plan price per tbclark3 below]\nHmmm... where are you getting Total Connect for $12.50? I'm paying $17 and thought that was a discount price.\n\nIt appears to me that IFTTT Pro should be adequate since it allows for webhooks, and it's $2.92/month.\n\nThanks for your conscientious support and your help!\n@austinmroczek How much work would it be to setup a new App Id using an account not associated with you and see if something changes?  This should be verifiable entirely using just the tests in the [total_connect_client](https://github.com/craigjmidwinter/total-connect-client) code, no? \n\nI'm been too busy at work since finding this thread and try anything.  Where is the developer portal to my own App Id for alarmnet/totalconnect2 to experiment with?  I've found a few different portals for honeywell, honeywellhome, resideo, etc.  But none of them let me set up anything except OAuth creds. \nIf it helps any, I coded a custom integration in Homebridge. It took me about a month since I don't code often. It was loosely based on someone else's code. And it worked like perfection until TC2.0 came out with an update, and then my logs showed Cloudflare protections that I couldn't seem to bypass. I then logged into totalconnect2.com, and I had to reset my password due to \"violation of terms\" So I gave up on it.\n> Hmmm... where are you getting Total Connect for $12.50?\n\nSorry I was remembering the price from a few years ago.  Just checked and I'm now at $15.95/month from Alarm Relay.\n\n> It appears to me that IFTTT Pro should be adequate since it allows for webhooks, and it's $2.92/month.\n\nSorry I must have been reading the Pro+ price. \n\n> How much work would it be to setup a new App Id\n\nThe ApplicationID we are using was copied from another system (I think SmartThings, maybe OpenHab) 6-8 years ago.  The API documentation just says to give your ID during a login request, but doesn't say anything about how to create or get an ID assigned.  \n\nIt's easy to change the ID in the total_connect_client code.  I actually did that earlier this morning, just added 1, but it didn't help. Other than random guessing, I don't know how we get a new ID.\n\nThere are Application ID's available via Google search.  This one came from a Honeywell discussion group and supposedly worked 2 years ago:\n91db1612-73fd-4500-91b2-e63b069b185c\n\n\nThanks but that ID doesn't work.\n\nPer the [API](https://rs.alarmnet.com/TC21api/tc2.asmx?op=LoginAndGetSessionDetails) it's supposed to be an integer.  I tried it anyways but got\n\n```txt\nServer was unable to read request. ---> There is an error in XML document (2, 320). ---> Input string was not in a correct format.\n```\n\nWe are currently using 14588\n> I wish I had more concrete answers. There is no insight into how the server works. It's a logical assumption that if Alexa works, so should this. However, in the past there were times when the TotalConnect app (iOS) worked but this did not, which is why I'm still holding out hope. Past outages have been up to a couple of days, and since today is Friday, maybe it extends over the weekend. If we still can't do anything by Monday my hope will quickly fade.\n> \n> I'm trying to work up some alternatives for folks. Possibilities are:\n> \n> * IFTTT can communicate with TotalConnect and Home Assistant (via Webhooks). However this requires an IFTTT \"pro\" plan that is $12.50/month which is the same price I'm paying for TotalConnect right now.  Have not tried this yet due to the cost.\n> * The newer Pro series panels support HomeKit.  I never bothered because I had the functionality I wanted.  I'll be testing this soon.  Assuming it works, this will probably leave most older, but still functional, alarm panels behind.\n\nI enabled the HomeKit support on my Pro series panel and works well, although doesn't do much for me since limited to only the HomeKit world (most automations are built in Home Assistant). \n> > I wish I had more concrete answers. There is no insight into how the server works. It's a logical assumption that if Alexa works, so should this. However, in the past there were times when the TotalConnect app (iOS) worked but this did not, which is why I'm still holding out hope. Past outages have been up to a couple of days, and since today is Friday, maybe it extends over the weekend. If we still can't do anything by Monday my hope will quickly fade.\n> > \n> > I'm trying to work up some alternatives for folks. Possibilities are:\n> > \n> > * IFTTT can communicate with TotalConnect and Home Assistant (via Webhooks). However this requires an IFTTT \"pro\" plan that is $12.50/month which is the same price I'm paying for TotalConnect right now.  Have not tried this yet due to the cost.\n> > * The newer Pro series panels support HomeKit.  I never bothered because I had the functionality I wanted.  I'll be testing this soon.  Assuming it works, this will probably leave most older, but still functional, alarm panels behind.\n> \n> I enabled the HomeKit support on my Pro series panel and works well, although doesn't do much for me since limited to only the HomeKit world (most automations are built in Home Assistant). \n\nYou could use the homekit controller integration to pass through the pro series panel to HA. \nOh no, reading this thread doesn't give me a lot of hope for the future :( \n> * The newer Pro series panels support HomeKit.\n\nNot to take things too off topic, but if you have multiple panels in your home could you get away with replacing one of them with a Pro series model for HA support or would you need to replace all of them?\n\nEdit: It appears the Pro series panels aren't compatible with Vista systems which I imagine would make upgrading panels prohibitive for a lot of folks.\nFWIW I got an IFTTT Pro trial going easily for arm/disarm and easily and the response time was less than 10 seconds. Hadn't logged in since before the pandemic. I expect it is not as fully featured as the integration, which I hope continues to be the solution. However, based on the responses above it sounds like the manufacturer couldn't care less about our use case so if your integrations are important you may want to test a backup approach in case the rug gets pulled out from everyone permanently.\n> > * The newer Pro series panels support HomeKit.\n> \n> Not to take things too off topic, but if you have multiple panels in your home could you get away with replacing one of them with a Pro series model for HA support or would you need to replace all of them?\n> \n> Edit: It appears the Pro series panels aren't compatible with Vista systems which I imagine would make upgrading panels prohibitive for a lot of folks.\n\nAs a Honeywell/Resideo integrator The ProA7 panels are a stand alone product and do not support the vista panels. However they do support a Pro Takeover module that allows the Vista aka 5800 series wireless devices to interface with the Pro Panel. So your motions, door contacts and glass breaks can be supported into it. The bad news is that the pro panel will not work with the vista keypads so you can\u2019t reuse them. \n\n\n\n> > * The newer Pro series panels support HomeKit.\n> \n> Not to take things too off topic, but if you have multiple panels in your home could you get away with replacing one of them with a Pro series model for HA support or would you need to replace all of them?\n> \n> Edit: It appears the Pro series panels aren't compatible with Vista systems which I imagine would make upgrading panels prohibitive for a lot of folks.\n\n\nAs a Honeywell/Resideo integrator, the new H3 panel might be the better option for upgrading systems that have Vista\u2019s in place. The ProA7 panels are a stand alone product and do not support the vista panels. However they do support a Pro Takeover module that allows the Vista aka 5800 series wireless devices to interface with the Pro Panel. So your motions, door contacts and glass breaks can be supported into it. The bad news is that the pro panel will not work with the vista keypads so you can\u2019t reuse them. \n\n> * The newer Pro series panels support HomeKit.  I never bothered because I had the functionality I wanted.  I'll be testing this soon.  Assuming it works, this will probably leave most older, but still functional, alarm panels behind.\n\nI'm using the Pro Panel with HomeKit directly and it works great. The single reason why I have a Home Assistant setup is for the Total Connect integration - and only because I wanted to automate \"Arm Stay Instant\" (no entry delay) because HomeKit has no way to do this - you can only toggle instant arming via the panel - it's not even available via the app or the website.\n\nSo hopefully this isn't the end. Thank You @austinmroczek for all your work on this.\n> > * The newer Pro series panels support HomeKit.  I never bothered because I had the functionality I wanted.  I'll be testing this soon.  Assuming it works, this will probably leave most older, but still functional, alarm panels behind.\n> \n> I'm using the Pro Panel with HomeKit directly and it works great. The single reason why I have a Home Assistant setup is for the Total Connect integration - and only because I wanted to automate \"Arm Stay Instant\" (no entry delay) because HomeKit has no way to do this - you can only toggle instant arming via the panel - it's not even available via the app or the website.\n> \n> So hopefully this isn't the end. Thank You [@austinmroczek](https://github.com/austinmroczek) for all your work on this.\n\nYou can arm stay instant in the app by going to the keypad, and typing your code followed by the number 7. However, I know this is dumb and they should be ashamed that it's not easier to arm this mode with the press of a button.\n@austinmroczek Not sure if this helps, but tracing the web interface, this is roughly how the authentication works. If I had more time I might be able to figure out how to grab the appid and locale using jsonpath. This script will get the session id which I hope can then be used for the other SOAP calls\n\n```\nfrom Crypto.PublicKey import RSA\nfrom Crypto.Cipher import  PKCS1_v1_5\nfrom jsonpath_ng import jsonpath, parse\nimport base64\nimport requests\nimport jwt\n\n\ndef encrypt_message(message, public_key_pem):\n    \"\"\"Encrypts a message using a public key from a PEM file.\"\"\"\n\n    # Load the public key from the PEM file\n    public_key = RSA.importKey(public_key_pem)\n\n    # Create a cipher object using PKCS1_OAEP padding\n    cipher = PKCS1_v1_5.new(public_key)\n\n    # Encrypt the message\n    encrypted_message = cipher.encrypt(message.encode())\n\n    # Encode the encrypted message in base64 for safe transmission\n    encoded_message = base64.b64encode(encrypted_message).decode()\n\n    return encoded_message\n\nif __name__ == \"__main__\":\n\n    response = requests.get('https://totalconnect2.com/application.config.json')\n\n    if response.ok:\n        config_json = response.json()\n        public_key = config_json[\"AppConfig\"][0][\"tc2APIKey\"]\n        client_id = config_json[\"AppConfig\"][0][\"tc2ClientId\"]\n        #jsonpath_expr = parse('$..langCulture[?(@.LanguageCulture==\"en\")]')\n        locale = 'en-US'\n        #jsonpath_expr = parse(\"$..brandInfo[?(@.BrandName=='totalconnect')].AppID\")\n        appid = 16808\n        \n\n    public_key_pem = '-----BEGIN PUBLIC KEY-----\\n' + public_key + '\\n-----END PUBLIC KEY-----'\n\n    username = \"username\"\n    encrypted_username = encrypt_message(username, public_key_pem)\n\n    password = \"password\"\n    encrypted_password = encrypt_message(password, public_key_pem)\n\n    data = {\n        'username': encrypted_username,\n        'password': encrypted_password,\n        'grant_type': 'password',\n        'client_id': client_id,\n        'locale': locale,\n    }\n\n\n    response = requests.post(\n        url='https://rs.alarmnet.com/TC2API.Auth/token',\n        data=data\n    )\n\n    if response.ok:\n        response_json = response.json()\n        if 'access_token' in response_json:\n            jwt_token = jwt.decode(response_json['access_token'], algorithms=\"HS256\", options={\"verify_signature\": False})\n            ids = jwt_token[\"ids\"]\n            session_id = ids.split(';',1)[0]\n\n\n    print(session_id)\n\n    data = f'<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetSessionDetails xmlns=\"https://services.alarmnet.com/TC2/\"><SessionID>{session_id}</SessionID><ApplicationID>{appid}</ApplicationID><ApplicationVersion>3.40.1.34</ApplicationVersion></GetSessionDetails></soap:Body></soap:Envelope>'\n    \n    response = requests.post(\n        url='https://rs.alarmnet.com/TC21API/TC2.asmx',\n        data=data,\n        headers={\n            'Content-Type': 'text/xml; charset=utf-8',\n            'SOAPAction': 'https://services.alarmnet.com/TC2/GetSessionDetails',\n        }\n    )\n\n    if response.ok:\n        print(response.text)\n```\nI'm also having this issue, hopefully it can get resolved.\naustinmroczek\u00a0thank you for your contribution!\n\nI tried to contact\u00a0my alarm monitoring provider and their \"tech\" has no idea what I'm\u00a0talking about.\nPer someone's suggestion\u00a0I think it would be very helpful if we start complaining\u00a0to our providers.\n\nDoes anybody have some good explanation that I can say / send to my provider about what\u00a0Resideo needs to do in order to restore\u00a0Home Assistant access\u00a0?\nI suppose if enough monitoring companies report that they are losing customers due to a loss of HA connectivity to TC2.0, Honeywell Resido may fix the issue.\n\nI would think that Nabu Casa would take action and advise us if loss of connectivity is due to a fee dispute or something else.\n\nNabu Casa seeks fee-free services on our behalf, but have been unsuccessful with MyQ and others, which devalues HA and TC2.0 for us automation enthusiasts.\n\nPersonally, a loss of TC2.0 connectivity leaves a big hole in my HA.\nI also contacted my alarm monitoring company and they stated they had no knowledge or previous reports of any issues. They promised to reach out to Honeywell's support team and let me know what they find out.\nSame issue, unable to connect.\nNothing new to contribute, but I am having the same issue and will report this to my monitoring company in hopes that Residio resolves this for us\nAlmost sounds like a single well written email that we can all send to our providers would make sense in this type of scenario. Most of our providers will not have any clue what we are even talking about, so something that explains the issue with technical support that can be sent in writing would be the way to go. I don't have the technical understanding of the issue to explain it, but happy to help anyway I can. This integration has been the primary reason I have been using home assistant!\n\nPersonally when my installers came in they had no idea how I was doing what I was doing when I showed them I already had Total Connect in HomeKit before it was supported. In fact, the last \"tech\" I had out for an unrelated issue didn't even know about the homekit integration (my original panel failed and had to be replaced).\nGreat idea!\n> This script will get the session id which I hope can then be used for the other SOAP calls\n\nWhat we really need is to listen for the ApplicationId in the LoginAnd.... call going from the web/app to the server.  There are four similar calls, not sure which one the web or app use.  There are also Authenticate... calls that are a possibility.  See https://rs.alarmnet.com/TC21api/tc2.asmx \n\n\nI had contacted resideo in 2020 for an issue related to TC Android mobile app and have their email addresses (not generic one). If someone is writing a detailed technical email, I can share their email ids. Not posting here to avoid spamming their mailboxes.\nAt this point, the biggest thing we need is open communication with Resideo/Honeywell, specifically whoever manages TotalConnect 2.0. Even if the answers they give aren't what we want (i.e. they are purposely blocking us), it would be better than guessing what's happening on the server end.\n\nIf folks are willing to try to contact Resideo, or their alarm company, please ask them to reach out to me. My discord is austinm6748 and email is austin@mroczek.org \n\nI sent the following to my alarm company. \n\n> I have monthly AlarmNet / TotalConnect service with account #########.  One of the reasons I use your service is because I could use TotalConnect to tie my alarm into my home automation system called Home Assistant (https://www.home-assistant.io/).  However, there seems to be a problem with the TotalConnect servers that is preventing use with Home Assistant.  See https://github.com/home-assistant/core/issues/136340\n> \n> I contacted Resideo / TotalConnect but all they would tell me is:\n> \n> \"All of the security panels/systems along the TC2.0 app are not supported by this channel. These are only sold, installed and supported, by professional security providers/installers. For technical information, account management or general documentation, you can use our tool: https://www.resideo.com/us/en/find-a-pro/ To find a local security provider/installer that carries/services and supports this products.\u201d\n> \n> Thank you\n\n\n> If someone is writing a detailed technical email, I can share their email ids.\n\nMy discord is austinm6748 and email is [austin@mroczek.org](mailto:austin@mroczek.org)\nI also e-mailed my provider.  Definitely couldn't hurt.\nI don't think the installers know anything about it.  I once had HA report a tamper issue with one of my smoke detectors, when TC2 and their own system showed everything was fine.  Service rep came out, and sure enough, the cover had not been properly put back on during the last maintenance.  He was stunned that 3rd party software picked that up when nothing else did.  I showed him HA, and he had never heard of it before.  \nToday I went into the TC2 app, and under the \"About\" setting, there's a \"provide feedback\" option that's asks for your email address and what comments you have.   I've received responses through this before.  I asked if they made any recent changes to restrict their API to limit 3rd party applications.  I referenced Home Assistant and said several hundred home automation enthusiasts were locked out and trying to figure out what happened.  I also asked that if they did change their API policy, they should communicate that.  We'll see what happens.  I'll report back if I get a response.  \nGood tip!  I sent this thru the TC2.0 Feedback link:\n\"Are there any recent changes to restrict the TC2.0 API to limit 3rd party applications?  I have been using Home Assistant with TC2.0 for a long time now, and I, along with several hundred home automation enthusiasts, are locked out and trying to figure out what happened.\n\nIf a change was made to TC2.0 to prevent Home Assistant from connecting to the TC2.0 API, please communicate this.\"\nI also sent feedback thru TC2.0 app and emailed to my dealer AlarmGrid. Will post if any reply shows-up. Its time to build something similar to \"ratgdo for MyQ garage door openers\". I have an app called L5100 Connect which connects to my Lynx panel directly over the same wifi network and perform all activities and display sensors' status without going thru cloud.\nSame issue. I e-mailed Resideo and Alarm Grid and provided the output directly from my simple Python program using the Total_connect_client library.\n\nclient = TotalConnectClient(username, password)\nTraceback (most recent call last):\n  File \"<python-input-5>\", line 1, in <module>\n    client = TotalConnectClient(username, password)\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 100, in __init__\n    self.authenticate()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 309, in authenticate\n    response = self.request(\n        operation_name,\n        (self.username, self.password, self.API_APP_ID, self.API_APP_VERSION),\n    )\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 246, in request\n    self._raise_for_retry(response)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/client.py\", line 159, in _raise_for_retry\n    rc = _ResultCode.from_response(response)\n  File \"/usr/local/lib/python3.13/site-packages/total_connect_client/const.py\", line 164, in from_response\n    raise ServiceUnavailable(\n        f\"Server returned empty response, check server status at {STATUS_URL}\"\n    ) from None\ntotal_connect_client.exceptions.ServiceUnavailable: Server returned empty response, check server status at https://status.resideo.com/\n\n@brownbloodspider thanks for the contacts.  I have sent a detailed email describing the problem and asking how we can help restore service. I hope we'll get feedback soon.  \n\nI will be disconnected most of Sunday and Monday.  I will not be able to post an update until very late Monday night. \n> Its time to build something similar to \"ratgdo for MyQ garage door openers\".\n\nI agree in principle, but alarm panels are significantly more complicated and it would be a large effort. If we can't get this server problem resolved, I'll certainly be thinking about this option.\n\n\n      \r\n  \r\n\r\n Wouldn't konnected be the alternative? I've been looking at it but don't know if the integration kit would work\r\n  \r\n  \r\n  \r\n  \r\n  \r\n  \r\n  \r\n\r\n  \r\n  \r\n>   \r\n> On Jan 25, 2025 at 4:25 PM,  <Austin Mroczek ***@***.***)>  wrote:\r\n>   \r\n>   \r\n>   \r\n>\r\n>\r\n>\r\n>   \r\n> >   \r\n> >\r\n> > Its time to build something similar to \"ratgdo for MyQ garage door openers\".\r\n> >\r\n> >   \r\n>   \r\n>\r\n> I agree in principle, but alarm panels are significantly more complicated and it would be a large effort. If we can't get this server problem resolved, I'll certainly be thinking about this option.\r\n>\r\n>   \r\n>\r\n> \u2014\r\n>  Reply to this email directly,   view it on GitHub (https://github.com/home-assistant/core/issues/136340#issuecomment-2614118888), or   unsubscribe (https://github.com/notifications/unsubscribe-auth/AFNKUWSOMVLOJ7XOGRVB5PT2MQFN3AVCNFSM6AAAAABVXNHF7WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMJUGEYTQOBYHA).\r\n>  You are receiving this because you commented.Message ID:  ***@***.***>\r\n>\r\n>   \r\n>   \r\n  \r\n  \r\n     \n> Wouldn't konnected be the alternative?\n\nIt may be a good starting point, but it seems to only be for wired alarm systems. Many of the panels used here have primarily wireless sensors. \n> > Wouldn't konnected be the alternative?\n> \n> It may be a good starting point, but it seems to only be for wired alarm systems. Many of the panels used here have primarily wireless sensors. \n\nYeah that's true, I've got both wired and wireless sensors, it would probably work for arming/disarming but not for monitoring zones right?\nHave the same issue. I also submitted Feedback in the TC app. \n\nI have three partitions in my setup and prior to this issue any status updates on arm/disarm etc would not update in HA for partitions 2 and 3 until I reloaded the TC Integration in HA to get the latest status on the partitions. I should probably open a new issue, but I thought I would share the issue here as well.\n\nThanks for all your efforts @austinmroczek. It's appreciated. \n> Wouldn't konnected be the alternative? I've been looking at it but don't know if the integration kit would work\n> [\u2026](#)\n\nI had no idea this existed! This might be exactly what I've been wanting so thank you for bringing this up.\n> > This script will get the session id which I hope can then be used for the other SOAP calls\n> \n> What we really need is to listen for the ApplicationId in the LoginAnd.... call going from the web/app to the server. There are four similar calls, not sure which one the web or app use. There are also Authenticate... calls that are a possibility. See https://rs.alarmnet.com/TC21api/tc2.asmx\n\n@austinmroczek, tracing through the HTTP requests made by the web app I don't see any `LoginAnd...` SOAP calls anymore. Looks like there's a new separate non-SOAP endpoint (https://rs.alarmnet.com/TC2API.Auth/token) that returns a JWT with a SessionID (as detailed in https://github.com/home-assistant/core/issues/136340#issuecomment-2613746391) and then that is passed back in with each SOAP API call.\n\nWould it be sufficient to drop @thor0215's code into the `authenticate` call in `total_connect_client.client` here and just set the token here: https://github.com/craigjmidwinter/total-connect-client/blob/master/total_connect_client/client.py#L320 ? I'll try it out a bit later\n> I also sent feedback thru TC2.0 app and emailed to my dealer AlarmGrid. Will post if any reply shows-up. Its time to build something similar to \"ratgdo for MyQ garage door openers\". I have an app called L5100 Connect which connects to my Lynx panel directly over the same wifi network and perform all activities and display sensors' status without going thru cloud.\n\n@sambeetm please share the info on the app w/o going to the cloud ?\n@austinmroczek I have a PR that I think fixes the issue: https://github.com/craigjmidwinter/total-connect-client/pull/243\nHas there been any update on this?\n> Has there been any update on this?\n\nhttps://github.com/craigjmidwinter/total-connect-client/pull/243\nhttps://github.com/craigjmidwinter/total-connect-client/issues/245\nhttps://github.com/craigjmidwinter/total-connect-client/pull/246\nNot that it matters, but for what it is worth, this is the response I got from AlarmGrid:\n\n> Hello Daniel,\n> \n> Resideo has been made aware of this issue and have reported it to engineering. They are currently investigating and working towards resolving this issue.\n> \n> We will provide an update once we have more information to share.\n> \n> Thank you!\nOnce this is pushed, will we need to reboot the integration or will it push to us automatically?\nHere's the status as of Monday night.\n\n**Summary:** Resideo seems to be turning off pieces of the old SOAP API (which we currently use) in favor a new API. We have to adapt all of our code accordingly.  We have a working fix that I hope to have in Home Assistant in the coming days.  However, depending on how quickly other pieces of the old API are turned off, other issues may pop up as we race to change all of the code to the new API.\n\n**Details:**\n- Someone in the TotalConnect team at Resideo responded to my email, but they pushed the issue to others and are awaiting their response. Hopefully we'll hear from them soon.\n- Thanks to the efforts of @thor0215 and @db3000 and help from some others, we discovered that the new API provided by Resideo allows us to log in and operate alarms.  \n- A basic fix is in place in total_connect_client version 2025.1.3 which is available on [pypi](https://pypi.org/project/total-connect-client/).  While the code is working, we don't have thorough or long term testing, so this \"hot fix\" likely has some hidden problems.  I can see panel status and arm and disarm the system from my development environment of Home Assistant.\n- I'm still working to get the new code pulled into Home Assistant so a simple update will fix the problem.  The new code requires some updates to our automatic testing regime which is taking me a bit longer than I wanted.  I hope to have an update pushed into Home Assistant soon, maybe Tuesday.  \n- Once an update is pulled into Home Assistant (either a version 2025.1.5 or 2025.2) users would just need to update and restart, and then it should work.\n- Brave souls could manually install the new version of total_connect_client in their Home Assistant.  If you know how to do that, it would be great to have some beta testers trying to find any issues. I'm purposely not explaining that here, because it will definitely break your warranty.\n- We hypothesize this whole issue is because Resideo is deprecating pieces of the old SOAP API in favor of the new API. Hopefully communication with Resideo will confirm this, or tell us what is actually going on.\n- Assuming our hypothesis is correct, Resideo may be in the process of deprecating other pieces we have not yet discovered, so other things may be broken or break in the near future.\n- We will move as quickly as we can to transition to fully transition to the new API. We will have to balance going fast against taking the time for thorough testing.\n\nI plan to post another update Tuesday night.\n\n", "created_at": "2025-01-29T00:55:57Z"}
